# Introduction to Digital Literacies for Online Learning

## Overview {-}

Welcome to Unit 1 of Learning with Technology! In this first unit, we begin the course by discussing...


### Topics {-}

This unit is divided into the following topics:

1. Understanding the Digital
2. Personal Learning Environments
3. Online Identity for Learning
4. Digital Literacies
  

### Learning Outcomes {-}

When you have completed this unit, you should be able to:

- Describe your engagement with digital technology
- Apply digital tools to support learning in an academic environment
- Explain what digital literacies mean for you in an academic and professional context
- Examine your digital footprint
- Build your professional online biography 
- Examine privacy concerns related to various platforms and tools
- Describe how to protect yourself and others in the digital environment.
 


### Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

```{block2, type='reflect'}

<span class="blockhead">Learning Activities</span>

- Watch the introduction video on ...and read... 
- Establish a personal learning environment by setting up your own course blog.
- Ilustrate your engagement with digital technology through a mind map.
- Publish your first blog post, introducing yourself to course participants.	
- Audit your own digital footprint to find out what exists on the internet about you
- Share what social media technologies you use to support learning and how you use them by posting in the community forum in Discourse.
- Build or update your professional online biography and the “About” page of your academic / course website.                                                                                                                                                                                                              	
- Post in Discourse, sharing a comment about your learning on this course. 
- Read an online article and annotate it using Hypothes.is.
- Search, evaluate, select, annotate, tag, and share resource links.
- Post in the Discourse forum, reflecting on the reasons why digital literacy matters to you
- Blog about your personal definition of digital literacies and the digital visitor / digital resident personal learning network (PLN) mapping exercise
- Take the Self-Check Quiz on Unit 1 concepts. (ungraded)  
 
**Note:** The learning activities in this course are designed to prepare you for the graded assigments in this course.  
You are strongly encouraged to complete them.


```

```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

- See the Assessment section in Moodle for assignment details and due dates.

```



### Resources {-}

- All resources will be provided online in the unit.  


## Understanding the Digital

We begin Unit 1 with an introduction to ...  

### Activity:  {-}

```{block2, type='reflect'}

Watch the video below to get an overview of ....  


Next, read the article on...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- Why is it important to ...  

```

### Activity: Reflective Journal {-}

```{block2, type='reflect'}

***Feel free to answer the questions above in your notes or Reflective Learning Journal***. 

<span class="blockhead">Introduction to the Reflective Journaling</span>

A reflective journal is simply a record of your thoughts. It is a reflection of the way you think and the manner in which you respond to your learning.  Journals can consist of traditional note taking, mind maps, pictures, stream-of-consciousness writing, recordings, quotes, sketches, or drawings: whatever you choose to include. Experiment and have fun. 
The purpose of journaling is to make you an active participant in your learning experiences as you engage in the various activities throughout the course’s readings, activities, and discussions with your instructor and your fellow students. Reflecting upon these learning events will help you gain a deeper understanding of the course materials and help integrate your learning into applied practice in your everyday life and work. 
Throughout the course, we will remind you to write in your journal, as we want to be sure you are actively learning the material. To assist you, we have provided you with questions you can ask yourself in order to get your creative energies flowing. Reflective journaling is an activity you can and should complete on a regular or daily basis, even outside of our scheduled course activities. 

<details>
<summary>**Common Questions Used for Reflective Journaling** - Click to expand</summary> 

- In your view, what were the most important points in the readings, videoclips, or discussions with your peers?  
- What information did you already know?  
- What new knowledge, ideas, or perspectives have you gained?  
- What information was easy to remember or learn? Why?  
- What concepts did you find more difficult? Why?  
- How can you apply this knowledge to your work or current experience?  
- How has this knowledge helped you to make sense of your current or previous experience?  
- Has your understanding of a personal or work-related situation changed after studying these concepts?  
- Did you agree or disagree with any of the material? If yes, how did you react and why?  
- If you could have the opportunity to engage in further learning, what would it be?  
- What further questions would like to ask the author of your readings?  
- What other articles, books or discussions would be of interest?  

*For any journal assignments in your courses, please refer to the specific questions and/or grading 
criteria to help you in your writing.* 

</details>
<br />


```

## Personal Learning Environments 

<!-- adding content from LIDA - to be edited & personalized! -->
...

The primary purpose of this topic is to enable you to set up your course blog, which will form the hub of your Personal Learning Environment (PLE). 

Blog posts are a useful way of reflecting on your learning and a means to network with your peers. 
It also provides our learning community with a way to see how you are getting on and to help where we can.


The purpose of a PLE is to put the learner at the centre of the online learning environment, which will be enabled by establishing a personal blog for this course. Using a course blog:

You will retain control of your data and learning outputs generated during this online course, even after the course is completed.
You get to choose:
- The blog service you would like to use, although we recommend WordPress as it is supported by TWU.
- Whether to accept comments on your blog from your peers
- Whether to register your blog for the aggregated course feed so that any posts tagged with the course code (LiDA101) will be harvested for the feed.


A key teaching philosophy of this course is to embed the acquisition of new digital literacies 
into your learning journey. Knowledge of how to use the Internet and social media technologies 
will better prepare you for life in a digital world.

If this is your first time blogging, you should spend time in setting up your personal digital 
learning environment.

In this course, you will also use social media technologies to interact with fellow students. 
The advantage is that you will control and retain access to all the content and learning artefacts 
you create during this course, even after its conclusion.

Please remember that your course blog and the social media technologies you use on this course 
are public, and that you take full responsibility for anything you publish. 
Do not disclose any confidential information and respect the privacy of your employer, colleagues 
and friends. In short, don’t say anything that you would not want to read on the Internet.


### Activity: ... {-}

```{block2, type='reflect'}

Download and read [“7 Things you should know about personal learning environments"](https://library.educause.edu/resources/2009/5/7-things-you-should-know-about-personal-learning-environments).
Read [Why you need a Personal Learning Network by Education Technology Solutions](https://educationtechnologysolutions.com/2014/07/why-you-need-a-personal-learning-network/).

<!-- update to more recent articles?  -->


<span class="blockhead">Questions to Consider</span>

After watching the video, consider the following:

- ...

```








### Activity: Setting up your course blog {-}

```{block2, type='reflect'}

As this is a course focusing on digital literacies, you are asked to establish 
a course blog, as this will improve your skills and enable you to network 
with your peers.   

We recommend using WordPress, as it is supported by TWU.

Follow the steps below to set up your blog.

1. Register an account and create a free blog on WordPress.com.
1. Determine the difference between the dashboard used for editing and the published view of your blog. (It is important to know the difference because, when you register your blog for the course feed, you must use the url for the public view of your blog).
- Do you know how to open the published (public view) of your blog in a new window?
- Have you added a browser bookmark to your dashboard and public version of your blog?

1. Complete your personal details for display on the “About” page of your blog.
- Can you see the updates on your “about” page in the published view of your blog?

1. Review and customise your blog settings from the dashboard according to your preferences.
- We recommend that you enable categories and tags on your blog.
- Consider whether you want to moderate all comments or, in the case of WordPress, you can also enable previously approved posters to post comments without moderation. Conduct a web search on “moderating blog comments” to find out more about the pros and cons on the flow of information when moderating comments.

1. Visit the appearance option on your dashboard and personalise your blog by:
- Changing: your theme, header image, background colours and/or image
- Add at least one widget to your blog — remember “less is more“. One or two of the following are functional choices: Archives, recent posts, categories or category cloud, and blogs I follow.

1. Draft a blog post, reflecting on your experience of this e-Learning activity on creating a blog.
Click on “save draft” (so you can review before publishing live on the web). Your reflection could for example:
- Introduce yourself and reflect on what you would like to achieve by maintaining a blog to support your learning
- Reflect on what you thought of the activity; Was it easy or hard?
- Share links to any additional resources you found useful in completing the tasks.
- Provide tips for future learners who will be completing this activity. If you were to set up a new blog again, what would you do differently?
- Add anything your readers may find interesting or useful.

1. Choose a photo to add to your blog post. 
- Be sure you have permission to upload the photo.  We sugest using an open licence site, such as pixabay or...
- Alternatively, upload your own photo, take a selfie or ask someone to take a photo of you working on this blog post challenge.
- Optional: Record a short video introduction and embed this in your blog post.

1. Review your draft post and, when you’re happy with what you’ve written, click on the “Publish post” button.

1. Add a category or tag for your post using the course tag: LDRS101

1. Post in the LDRS 101 Discourse forum to let your peers know the web address of your blog and ask them to post a comment. This will give you the opportunity to experience how comments function on your blog and to test if they are working properly.

```


## Online Identity for Learning 

add intro paragraph

[Your digital footprint matters](https://www.internetsociety.org/learning/digital-footprints/), published by the Internet Society.

https://www.youtube.com/watch?v=Ro_LlRg8rGg&t=1s - Four Reasons to Care About Your Digital Footprint



Julia Angwin, author of “Dragnet Nation: A Quest for Privacy, Security, and Freedom in a World of Relentless Surveillance” attempted to erase her digital footprint. 
Watch this short CBS This Morning interview with Julia:


...

### Activity: Digital Footprint Audit {-}

```{block2, type='reflect'}

In this activity you will audit your own digital footprint in order to find out what exists on the internet about you, and reflect on what you want your online identity to be.  Follow the steps below to begin.

1. Conduct a Google search of your own name (using an incognito or private window in Chrome or Firefox). Search for your first name and surname without parenthesis (for example: snow white) and then with parenthesis (for example: “snow white”). Explore the results of your search.
1. Conduct a Google search of your name with the name of current and previous employers.
1. Conduct a Google search of your name with the name of previous schools you attended.
1. Expand your search to include social media sites, for example: “snow white” twitter; “snow white” facebook; “snow white” youtube etc.
1. Note any interesting or surprising findings.

<span class="blockhead">Questions to Consider</span>

After watching the video, consider the following:

- ...

```



### Activity: Blog: My Digital Footprint {-}

```{block2, type='reflect'}

Prepare and publish a short blog post of about 250 to 300 words focusing on what you hope to achieve with your online digital identity for learning. Your post can include:

1. Optional reflection: You may want to include a reflection(s) on the outcomes of your footprint audit. Remember that your blog post is public, so only share what you are comfortable sharing with the world. You don’t need to be specific; for example, you can generalise: I am satisfied with my digital footprint because … or I would like to improve my digital footprint for learning because …

1. Professional versus private: Consider how you want to separate your “private” online identity from your professional and / or learning identity. If you already maintain an online presence (existing blog, twitter and/or facebook accounts) think about how you will separate professional / learning posts from private and social life interactions online. For example, maintaining a separate course or learning blog is one way to achieve this distinction. Will you link your personal online identities (e.g.an existing Twitter username or Facebook account) with your learning blog? Will you link your professional online identity (e.g. published online biography on your employer’s web site) with your learning blog?

1. Objectives: List a few objectives for developing or improving your online identity.

1. Remember to add a category or tag to your post using the course tag: LDRS101 (This is needed to harvest links to posts from registered course blogs for the course feed.)

Remember: You are in charge of what you post online and deciding what you would like to share for your digital identity for the purposes of this course. Don’t share high risk personal details like physical address, date of birth, name of first pet etc., which may make it easier for identity thieves to appear more credible. If unsure, consult online resources for internet safety; for example Netsafe New Zealand. (replace resource)

!! Note that we will cover online identity in more depth in Unit 5.

```



## Digital Literacies

In this unit we've started discussing 'the digital'; you have started a blog (part of your PLN), and you've examined your own digital identity.  In our final topic, we want to begin to define digital literacies, and continue to build digital skills.



### Activity: ... {-}

```{block2, type='reflect'}

...

<span class="blockhead">Questions to Consider</span>

After watching the video, consider the following:

- ...

```



## Summary {-}

In this first unit, you have had the opportunity to learn about ...



## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Quizzes 1 & 2</span>

After completing this unit, including the learning activities, you are asked to complete ...

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- Describe your engagement with digital technology
- Apply digital tools to support learning in an academic environment
- Explain what digital literacies mean for you in a tertiary education context
- Examine your digital footprint
- Build your professional online biography 
- Examine privacy concerns related to various platforms and tools
- Describe how to protect yourself, other students and colleagues, to stay safe in the digital environment.
 

```

This is text <abbr title="This is the definition of the word <b>this is emphasized</b>">Word To define</abbr> this is more text