# Connecting Ideas for Learning


## Overview {-}


### Topics {-}

This unit is divided into the following topics:

1. Sense-making through Hyperlinks
2. Sense-making through Taxonomies
3. Note-Taking
4. Concept Maps
5. Digital Tools to Support Learning
  

### Learning Outcomes {-}

When you have completed this unit, you should be able to demonstrate your ability to achieve the following course outcomes:

- Build and customize technology-integrated workflows to enhance and enrich your learning journey.  
- Practice evaluative judgment to document your process of learning in complex domains of knowledge.  
- Evaluate digital tools, platforms, and interactions based on ethical principles.  
 


### Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.


```{block2, type='reflect'}

<span class="blockhead">Learning Activities</span>

- ...
- ...
 
**Note:** The learning activities in this course are designed to prepare you for the graded assigments in this course.  
You are strongly encouraged to complete them.


```

## Sense-making Through Hyperlinks

In higher education, your task as an undergraduate is to build on the skills you bring from high school and apply those skills in a much more focussed field of study. Previously, you might have been able to succeed in school by having a great memory, but increasingly in university, you will be asked to do much more. You will be required to understand the theoretical basis of ideas (analysis) and also make connections between ideas to create new ideas (synthesis). This may feel challenging at first, but you will learn.

One of the challenges is that there is simply far too much information for you to analyze for any task that you might need to do for an instructor. In a previous unit, you learned some basic skills in finding and managing resources that you will need, and in this unit, you will learn some ways to begin to analyze and synthesize information and documents in a systematic way.

If you learn this workflow well, and learn how to customize it to your needs (that's synthesis), you will be ahead of the game when it comes time to complete papers in other courses.

The key to this component of your workflow is the lowly [hyperlink](https://en.wikipedia.org/wiki/Hyperlink){target="_blank"}. You likely know that if you click or tap on that highlighted word, you will be taken to another website, in this case, the wikipedia article on hyperlinks. That is a hyperlink and it is the most basic unit of the entire internet, which is simply a massive collection of documents all linked together. At it's most basic form, a hyperlink is simply a connection between two documents where a hyperlink in one document allows you to open the second document.

In this workflow, instead of just linking two documents together, you will link two ideas together (by linking documents). Your Obsidian vault is essentially a website that is only accessible on your computer, and instead of links going to documents on other servers, you link to documents within the vault (although you can still link to the web).


<!--


### Linking in Obsidian {-}


notes below from LIDA https://course.oeru.org/lida101/learning-pathways/learning-in-a-digital-age/reading-and-note-taking/
-->

## Note-Taking

Listening and note-taking

In this section we will listen and take notes from watching a video recording. The advantage of online video is that you can pause playback, or even increase the playback speed if you like. 

Some learners prefer taking notes with pen and paper, but in this activity you will be required to use a note-taking application. You can, always use pen and paper to prepare your first draft before recording a digital text version of your notes. Most citation management tools provide note taking capabilities which you can associate with items stored in your library, however for the purposes of this activity you will directed to use Simplenote (an open source tool) because we will be using features of this tool for other course activities.

### Activity: Listening & Note-taking {-}

```{block2, type='reflect'}

Read the following articles: 
- [What’s the best, most effective way to take notes?](https://theconversation.com/whats-the-best-most-effective-way-to-take-notes-41961){target="_blank"} published by The Conversation.
- [Effective listening and note taking](https://www.student.unsw.edu.au/note-taking-skills){target="_blank"} published by University of New South Wales.

Next, watch [Should You Take Notes on Paper or on a Computer? - College Info Geek](https://www.youtube.com/watch?v=gsb-U8bZpig){target="_blank"}



```

### Activity: Open Video and Audio Lectures {-}

```{block2, type='reflect'}

Search for a video or audio lecture on a topic of interest. Use your advanced search skills or browse the following sites to find a suitable recording aligned with your interests.

- [Open culture](https://www.openculture.com/freeonlinecourses): Over 30,000 hourse of free audio and video lectures. 
- [Open Yale courses](https://oyc.yale.edu/){target="_blank"}: Free and open access to a selection of introductory courses including video lectures from Yale University. 
- [Open learning at Harvard](https://extension.harvard.edu/online-learning/){target="_blank"}: Series of video lectures from Harvard University. 
- [MIT Opencourseware](https://ocw.mit.edu/search/?f=Lecture%20Videos&f=Lecture%20Audio&s=department_course_numbers.sort_coursenum){target="_blank"}: Series of audio and video lectures from Massachusetts Institute of Technology. 
- [Tedx talks](https://www.ted.com/){target="_blank"}: Extensive database of video presentations in the form of short, powerful talks. (See also [list of topics](https://www.ted.com/topics){target="_blank"}). 

Using Obsidian, record your notes from the lecture.
- The first line is used for the title of the note.  
- Remember to include a link to the source of the information.  
- Use tags  


```


Reading and note-taking 
In this section, you will demonstrate your note-taking skills based on reading an academic publication. 

The challenge which follows also incorporates digital skills associated with semantic content markup using the Markdown markup language. Semantic markup is an important digital skill which separates formatting (e.g. headings, bold, italics, lists etc.) from the content using designated characters without the use of rich text editors. This provides the capability to use plain text files that can be converted to formatted text online. Markdown is one of many markup protocols, and is used here to demonstrate the principles of semantic markup.

### Activity: Reading & Note-taking {-}

```{block2, type='reflect'}

Read the following articles and take notes in Obsidian.  
- [Effective note taking](https://www.student.unsw.edu.au/effective-reading-and-note-taking){target="_blank"} published by the University of New South Wales. 
- [Reading for Understanding: The SQW3R Method](https://www.student.unsw.edu.au/reading-understanding){target="_blank"} published by the University of New South Wales. 
- [How to (seriously) read a scientific paper](https://www.science.org/content/article/how-seriously-read-scientific-paper){target="_blank"}

Try using Markdown to format your text.
- [Basic formatting syntax](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax){target="_blank"} - Using Markdown in Obsidian

```


### Activity: Writing a Summary of your Readings {-}

```{block2, type='reflect'}

1. Search for a peer reviewed journal article in support of a research topic of interest.
1. Remember to add the source to your citation management tool, Zotero.
1. Prepare a summary of the journal article based on this example.
1. Use the Markdown formatting in Obsidian. Your summary must at a minimum demonstrate the following text formats:
 - Headings and subheadings
 - Bold and italics
 - Numbered or unordered list
 - Labelled link
 - Horizontal rule
 - Block quote for one or more citations from the article

1. Copy your summary prepared in Obsidian and paste this text summary into Zotero using the notes feature so that you have a copy for your personal library as backup.

1. Reflect on your progress in practicing these digital skills.  Share you thoughts in your Reflective Journal and/or in Discourse.


```



### Activity: Digital skills versus literacies {-}

```{block2, type='reflect'}

In this activity, we will review an article on the difference between digital skills and digital literacies using Hypothes.is – an online social annotation technology.


Purpose
Read an online article and annotate it using Hypothes.is.

Tasks

1. Read the Hypothes.is “Quick start guide for students”
1. Create an account on Hypothes.is. Here is the registration link
We recommend that you use the Chrome browser (download here) and install the Hypothes.is extension. Alternatively, you can annotate web pages directly from the Hypothes.is website by pasting the link into the text area after you have logged into the site. If you are working on a mobile device, please follow these instructions: How to use Hypothes.is on mobile devices.
1. Read the following article: Knowing the Difference Between Digital Skills and Digital Literacies, and Teaching Both
1. Activate the annotations after logging in to Hypothes.is and click on the search icon () and enter the course code (LiDA101) to filter posts for this course from the public feed.
1. Annotate or reply to posts by visiting the annotation page (You will need to be logged into the Hypothes.is site to post.)
1. Remember to tag your posts using the course code: LDRS101 (The course tag is required to harvest posts for the course feed.)

```


```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

- See the Assessment section in Moodle for assignment details and due dates.

```



### Resources {-}

- All resources will be provided online in the unit.  


## Topic

content

<!--
comment
-->



### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```

## Topic

content

<!--
comment
-->



### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```

## Topic

content

<!--
comment
-->



### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```


## Summary {-}

In this unit, you have had the opportunity to learn about ...



## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Quizzes 1 & 2</span>

After completing this unit, including the learning activities, you are asked to complete ...

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- ...
- ...
 

```
