# Building Your Online Presence

## Overview {-}

Welcome to Unit 4!  In previous units, you've been introduced to the world of digital literacies and how to use various tools for organizing and connecting ideas. You have started to build a workflow to help you learn more effectively, and have applied the critical skill of metacognition to explain your process for learning. 

Now, let's delve into the next phase of our learning journey.

In the second half of the course, you will continue to build your digital skills and use critical thinking to record your learning process. Our attention will move from creating a personal collection of ideas to presenting your learning in a more open platform. Note that you wil decide how public you want to be. We'll also consider why sharing knowledge is important and explore user-friendly ways to do so while still maintaining your control over your work and handling privacy matters. During this unit, you'll get the chance to create a blog, discover your digital footprint, and assess various digital tools.

### Topics {-}

This unit is divided into the following topics:


1. Personal Learning Environments 
2. Building a Learning Blog
3. My Digital Footprint
4. Evaluating Digital Tools

<!--
//todo #4
-->
 

### Learning Outcomes {-}

When you have completed this unit, you should be able to:

- Create a personalized narrative to document and express your learning process
- Examine your digital footprint and develop a positive digital online identity
- Evaluate digital tools, platforms, and interactions based on ethical principles
- Critically evaluate the affordances and restraints of digital tools and platforms
- Identify the digital skills needed in your field of study
- Describe how to protect yourself, other students and colleagues, to stay safe in the digital environment.
- Practice evaluative judgment to document your process of learning in complex domains of knowledge

<!--

Course Learning Outcomes related to this unit: 
- Practice evaluative judgment to document your process of learning in complex domains of knowledge
- Create a personalized narrative to document and express your learning process
- Evaluate digital tools, platforms, and interactions based on ethical principles
-->


### Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.


```{block2, type='reflect'}

<span class="blockhead">Learning Activities</span>

- Create a new blog on WordPress and personalise your blog site.
- Document and share your learning experience by posting a blog entry.
 
**Note:** The learning activities in this course are designed to prepare you for the graded assigments in this course.  You are strongly encouraged to complete them.


```

```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

- See the Assessment section in Moodle for assignment details and due dates.

```



### Resources {-}

- All resources will be provided online in the unit.  

```{block, type='feedback'}
***Resource Reminders***  
>*Be sure to add resources to your Zotero library you find relevant to your personal learning journey.*  
>*Your peers are a resource! Reach out to your online community for support, and be sure to share resources and insights.* 
```

**Resource Reminders**  
>*Be sure to add resources to your Zotero library you find relevant to your personal learning journey.*  
>*Your peers are a resource! Reach out to your online community for support, and be sure to share resources and insights.* 



## Personal Learning Environments 

The primary purpose of this topic is to enable you to set up your course blog, which will form the hub of your Personal Learning Environment (PLE). Blog posts are a useful way of reflecting on your learning and a means to network with your peers. It also provides our TWU learning community with a way to see how you are engaging with the course and to help where we can. The purpose of a PLE is to put the learner at the centre of the online learning environment, which will be enabled by establishing a personal blog for this course. 

So what is a Personal Learning Environment?

> 'Personal Learning Environments are systems that help learners take control of and manage their own learning. This includes providing support for learners to set their own learning goals, manage their learning; managing both content and process, communicate with others in the process of learning, and thereby achieve learning goals. A PLE may be composed of one or more sub-systems: As such it may be a desktop application, or composed of one or more web-based services.' [PLE Wiki](https://edutechwiki.unige.ch/en/Personal_learning_environment)

> A Personal Learning Environment is "a structure and process that helps learners organize the influx of information, resources and interactions that they are faced with on a daily basis into a personalized learning space or experience. In a PLE, the learner develops an individualized digital identity through the perceptual cues and cognitive affordances that the personal learning environment provides, such as what information to share and when, who to share it with, and how to effectively merge formal and informal learning experiences ([Castañeda, Cosgrave, Marín, Cronin, 2016](https://naerjournal.ua.es/article/view/v6n1-introduction#)) cited in [Personal Learning Environments: Research-Based Practices, Frameworks and Challenges](https://naerjournal.ua.es/article/view/v6n1-introduction).

What elements of the two definitions resonate with you?  How do you organize your daily interations and influx of information? How do you share your learning with others? What are your learning goals? 


### Activity: What is a PLE? {-}

```{block2, type='reflect'}

Before you start building your PLE, read the following article:  

- [“7 Things you should know about personal learning environments"](assets/u4/U4_7-things-you-should-know-about-PLNs.pdf)


<span class="blockhead">Questions to Consider</span>

After reading the article, consider the following:

- How do PLEs promote authentic, student-centred learning?
- What are the benefits of a PLE?  How would it benefit you?
- What tools do you currently use as part of your learning environment?

Finally, consider the approach taken at TWU as it supports inquiry-rich learning.  As you watch the short video below, think about how you could use your PLE to enrich your learning at TWU.

[Watch: *Inquiry-Rich Learning*](https://www.youtube.com/watch?v=SCa9Nt3X1vU){target="_blank”}

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/SCa9Nt3X1vU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

```

## Building a Learning Blog

In the next activity, you will gain first hand experience in using blog technology for publishing your own course site. You will “declare” yourself online using your PLE (as an alternative to posting an introduction in a closed course forum typically used in a conventional online course). Note that TWU online courses often use Moodle Discussion Forums to facilitate conversations.  By using a platform such as Wordpress, you can retain the contents of your posts, as well as the comments of your peers.  In an LMS (Learning Management System) such as Moodle, you may lose access to what you have posted in discussions, and more importantly, conversations with your peers.  As you create your personal blog in WordPress (or your own selective blog site), you control your data and who can see it.

You will retain control of your data and learning outputs generated during this online course, even after the course is completed.
You get to choose:

- The blog service you would like to use, although **we recommend WordPress as it is supported by TWU**. 
- Whether to accept comments on your blog from your peers
- Whether to register your blog for the aggregated course feed so that any posts tagged with the course code (LDRS101) will be harvested for the feed.


A key teaching philosophy of this course is to embed the acquisition of new digital literacies into your learning journey. Knowledge of how to use the Internet and social media technologies will better prepare you for life in a digital world. If this is your first time blogging, you should spend time in setting up your personal digital learning environment. Please remember that your course blog and the social media technologies you use on this course are public, and that you take full responsibility for anything you publish. Do not disclose any confidential information and respect the privacy of others. In short, don’t say anything that you would not want to read on the Internet.


### Activity: Setting Up Your Course Blog {-}

```{block2, type='reflect'}

As this is a course focusing on digital literacies, you are asked to establish a course blog, as this will improve your skills and enable you to network with your peers. We recommend using WordPress, as it is supported by TWU. WordPress is an open source website builder and is one of the most popular systems out there because of its versatility. If you already have your own website or you have previous experience using WordPress, you may set up your blog on it and skip the set-up steps described below, but you still need to complete the learning activities.

Watch the following video tutorial on how to create a website using WordPress. This video provides you with an overview of all the necessary steps. Do not worry if you start to feel overwhelmed — we will break these steps down for you one by one in the learning activities in this course.


<div class ="video-container">

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/f45737c6-fc7b-4c6e-a13f-f656c808ea06?autoplay=false&showinfo=true" allowfullscreen style="border:none; position: absolute; top: 0; left: 0; right: 0; bottom: 0; height: 100%; max-width: 100%;"></iframe>


</div>


> We are here to help you create your site, so do not hesitate to ask for technical support. Below you will find a number of resources, but if you get stuck, please reach out on Discourse, or email elearning@twu.ca

To get started on creating your site we suggest the following steps:

<details>
<summary>**1. Sign up to create a website**</summary>

Go to **[create.twu.ca](https://create.twu.ca/)** to sign up for your free WordPress site. *Please read all the prompts and instructions carefully!*
Be sure to read the Privacy Statement carefully before clicking “I Agree.” The information provided gives you excellent guidance regarding digital citizenship, privacy, and how to build a professional digital persona.

You will be prompted to **create a domain name**, which is your website’s address on the Internet. Often this is referred to as a URL (Uniform Resource Locator). This is what your users will type in their browsers to reach your site. Make sure that you choose a domain name that is related to you, easy to pronounce and spell, and easy to remember. Once you have done that, we suggest you write all this information somewhere you can access it easily – just in case. 

You will also be asked to **select a theme** for your website. You are free to choose any template you wish. TWU Spark, TWU Hope, and TWU Spartans portfolio are simple to set up and provide easy navigation.

When you choose your theme, your new site will come with a simple menu and instructions for portfolio and website creation. 

When you have activated your site (look for a notification in your TWU email), then you are ready to create.  

 </details>

<details>
<summary>**2. Explore your dashboard**</summary>

The dashboard is the initial area you see when you log in to TWU Create. It’s the centre for your site management and where you create content. From the Dashboard you can navigate to content, settings, themes, plugins, and more.

When logged in to TWU Create, you will always have access to an **admin menu** visible on your sites. From the menu item that is the name of the blog (second from left), you can find the link to the dashboard. While in the dashboard, the same menu can be used to return to the front view of your site.

Determine the difference between the dashboard used for editing and the published view of your blog. (It is important to know the difference because, when you register your blog for the course feed, you must use the url for the public view of your blog).  
*Progress check:*  
- Do you know how to open the published (public view) of your blog in a new window?  
- Have you added a browser bookmark to your dashboard and public version of your blog?  

**Help Tips:** When you are in the site administration area of your site, you can get tips on what you are doing by clicking the “Help” menu on the top-right corner. Click on "Help" and read through the Overview describing the elements of the dashboard.

insert - Animation showing location of WordPress help tab - from https://create.twu.ca/eportfolios/wordpress/ 

 </details>


<details>
<summary>**3. Review your settings**</summary>

Review and customise your blog settings from the dashboard according to your preferences. 

-   
**Enable Categories and Tags**
We recommend that you enable **categories** and **tags** on your blog.  
**Categories** are best used for broad groupings of topics. For example, if you’re creating a site that reviews pop culture, you might use categories such as Books, Film, and TV.

**Tags** are more specific keywords that you want to use to associate related content. For example, if you were creating a site that reviews pop culture, you might want to use tags such as science fiction, horror, and action adventure.

You can combine the two! For our review site example, you might be reviewing a romantic comedy. You can assign the broader category Film to the post, then give it some more specific tags such as romantic comedy, or even use the name of the actors and director as tags. People who view that post could use the tags to find related posts around that topic.

**Set up Comments Settings (Optional)**  
WordPress comes with a built-in comment system allowing your users to leave comments on your posts. This comment system is great for user engagement, but it can also be targeted by spammers as well. If you don't want comments on your posts, then ensure that the 'Allow comments' box is unchecked at the bottom of the editor page.  

If you do want comments, but want to manage the spam, you’ll need to enable comment moderation on your website.

Visit Settings » Discussions page and scroll down to ‘Before a comment appears’ section. Check the box next to ‘Comment must be manually approved’ option.

</details>

<details>
<summary>**4. Personalise your blog**</summary>  
Visit the appearance option on your dashboard and personalise your blog by:   
- Changing your theme, header image, background colours and/or image  
- Add at least one widget to your blog.  Remember —  “less is more“. One or two of the following are functional choices: Archives, recent posts, categories or category cloud, and blogs I follow.  

You need to hit the **“Save”** button to save your changes.

 </details>

<details>
<summary>**5. Add a page & a post**</summary>

Pages and posts are where the content is housed on WordPress. The biggest difference between the two is that posts are timestamped, whereas pages are timeless.

**Pages** are for static content. They do not need a publish date. Use pages you want your visitors to always be able to see that content in that spot, no matter when they visit.

**Posts** are for timely content. They have a publish date, and they are displayed with the newest content at the top (reverse chronological order) of your site’s blog page. Older posts can “fall off” the blog page (the content is still kept, but no longer visible). Posts are what you should think of when you hear the term “blog post.” Usually posts have a comment section, and this is where viewers can write a comment in response to your post. This may be a handy way to receive feedback from your peers. Also, you can categorize or tag your posts, which is useful to help readers locate posts on your blog.


To add a new Page or Post, click the Pages or Posts menu option and then click the Add New link underneath.  Another way is to hover your cursor over Pages or Posts and click the Add new link in the fly-out menu.

***BLOG CHALLENGE!***  

**Edit a Page:** Complete your personal details for display on the “About” page of your blog.  
- *Progress check:* Can you see the updates on your “about” page in the published view of your blog?


**Edit a Blog Post:**  Reflect on your experience of this activity on creating a blog.
Click on “save draft” (so you can review before publishing live on the web). Your reflection could for example:  
- Introduce yourself and reflect on what you would like to achieve by maintaining a blog to support your learning  
- Reflect on what you thought of the activity; Was it easy or hard?  
- Share links to any additional resources you found useful in completing the tasks.  
- Provide tips for future learners who will be completing this activity. If you were to set up a new blog again, what would you do differently?  
- Add anything your readers may find interesting or useful.  

 </details>

<details>
<summary>**6. Add media**</summary>

Using different types of media to represent your artifacts is a great way to make your portfolio dynamic and keep your audience engaged. Text-heavy pages can get cumbersome regardless of how you arrange it. Media can help with breaking up content or replacing text all together. Consider how you can “show what you know” rather than just simply telling. Media can also be an alternative to simply hyperlinking all your artifacts. Instead of sending your audience off to another site or tab, media can be embedded (see [Media Library](https://create.twu.ca/eportfolios/wordpress/media-library/)) to keep your audience contained to your page.

The Media Library on your WordPress site houses the media you upload to your site. WordPress supports a variety of media types such as images, audio, video, and documents. We do suggest that you host your video files in your TWU Microsoft Stream account for optimal playability. Other types of media are typically uploaded and inserted into the text editor when writing a post or page.

***BLOG PHOTO CHALLENGE!***

**Choose a photo** to add to your blog post.   
- Be sure you have permission to upload the photo.  We suggest using an open licence site, such as [Pixabay](https://pixabay.com/), [Unsplash](https://unsplash.com/), [Pexels](https://www.pexels.com/), [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page), or [Flickr](https://www.flickr.com/search/?text=pho&license=2%2C3%2C4%2C5%2C6%2C9).  
- Alternatively, upload your own photo, take a selfie or ask someone to take a photo of you working on this blog post challenge.  


<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/W89wPcVU60c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/9admKGpM3A0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

***BLOG VIDEO CHALLENGE!*** (Optional)

You may find as you continue the course that you want to share videos you find on the web, or perhaps even your own!  

If you're up for the challenge, consider recording a short video introduction and embed this in your blog post.

Here is a tutorial on how to add a Youtube video or embed one of your own videos to your blog:

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/3hCMpnok2Kw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

 </details>

<details>
<summary>**7. Publish!**</summary>

Review your draft post and, when you’re happy with what you’ve written, click on the **“Publish post”** button.

 </details>

<details>
<summary>**7. Share your blog**</summary>

Add a **category** or **tag** for your post using the course tag: LDRS101

Post in the **LDRS 101 Discourse forum** to let your peers know the web address of your blog and ask them to post a comment. This will give you the opportunity to experience how comments function on your blog and to test if they are working properly.


 </details>


<details>
<summary>**Additional Customizations**</summary>

When you’re ready to start customizing your blog and putting content in, check out some tutorials available to you:

- [TWU's Wordpress Support Page](https://www.twu.ca/academics/academic-professional-support/online-learning-resources/wordpress)

- TWU's Wordpress Video Tutorials - new sharepoint address?

- [WordPress Support Website](https://wordpress.com/support/)

- [Beginner’s guide for WordPress](https://www.wpbeginner.com/start-here/) by WPBeginner

- [WordPress Tutorials](https://onlineacademiccommunity.uvic.ca/wordpress-tutorials/) from University of Victoria


 </details>


> If you are confused about anything it is always good to do an initial Google or YouTube search, reach out on Discourse, or email elearning@twu.ca


```

Congratulations!!  You created your PLE for TWU!


## My Digital Footprint 

Now that you have started your course blog and introduced yourself online, let's examine your existing online identity.  If your future employers were to perform a google search for your name, what would they find?  What would you want them to find?  As we examine online identities in this topic, we will ask you to consider how you can improve your digital identity in support of your online learning, as well as future employment prospects.

First, let's clarify some key terms.

We need to distinguish between the technical and human elements of online identity. In this course, we are more interested in the human side of online identity, but in part, this is determined by how technology automates the process of building your digital footprint.

>**Digital identity** refers to the information utilized by computer systems to represent external entities, including a person, organization, application, or device. When used to describe an individual, it encompasses a person's compiled information and plays a crucial role in automating access to computer-based services, verifying identity online, and enabling computers to mediate relationships between entities. Digital identity for individuals is an aspect of a person's social identity and can also be referred to as online identity. ([Wikipedia](https://en.wikipedia.org/wiki/Digital_identity): Online).

>**Digital footprint** or digital shadow refers to one's unique set of traceable digital activities, actions, contributions, and communications manifested on the Internet or digital devices. Digital footprints can be classified as either passive or active. The former is composed of a user's web-browsing activity and information stored as cookies. The latter is often released deliberately by a user to share information on websites or social media. While the term usually applies to a person, a digital footprint can also refer to a business, organization or corporation. ([Wikipedia](https://en.wikipedia.org/wiki/Digital_footprint):Online).


### Activity: What is a Digital Footprint? {-}

```{block2, type='reflect'}

Watch the following video and consider the steps you would take to control your digital footprint.

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/dmQGq_FNBpE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

```

### Activity: Who am I Online...and Why Should I Care? {-}

```{block2, type='reflect'}

Read the following articles:

- [Understanding your Online Identity](assets/u4/U4_Understanding-your-Online-Identity-An-Overview-of-Identity.pdf).
- [How To Manage Your Digital Footprint: 20 Tips for Students](https://research.com/education/how-to-manage-digital-footprint)

<span class="blockhead">Questions to Consider</span>

Consider the following questions:

- How does your real-world identity differ from your online identity?  
- What factors inhibit or support the sharing of information in building an online identity?  
- What is the value of an online identity for learning?  

> Reminder: As you view online resources in this course, feel free to annotate and discuss web resources publicly in support of your learning. (Digital Tools: Hypothes.is, Discourse, WordPress, etc.)

In addition to evaluating who you are online, ask yourself, "Why Should I Care?"

First, watch the following video, [Four Reasons to Care About Your Digital Footprint](https://www.youtube.com/watch?v=Ro_LlRg8rGg)

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Ro_LlRg8rGg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

Next, select from these resources to inform your views:

- [Students turn to Internet to build online presence, showcase work](https://www.huffpost.com/entry/students-turn-to-internet_b_3518598), published on Huffingtonpost.
- [Your Online Presence](https://help.open.ac.uk/your-online-presence) published by the Open University
- [10 Ways to Build your Online Identity](https://www.careercast.com/career-news/10-ways-build-your-online-identity)
- UBC's [Digital Tattoo project](https://digitaltattoo.ubc.ca/)

Finally, consider how much someone could find out about you from your digital footprints.  Here's an interesting video that might cause you to reconsider what you post online.

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/F7pYHN9iC9I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


```


### Activity: Digital Footprint Audit {-}

```{block2, type='reflect'}

In this activity you will audit your own digital footprint in order to find out what exists on the internet about you, and reflect on what you want your online identity to be.  Follow the steps below to begin.

1. Conduct a Google search of your own name (using an incognito or private window in Chrome or Firefox). Search for your first name and surname without parenthesis (for example: snow white) and then with parenthesis (for example: “snow white”). Explore the results of your search.
1. Conduct a Google search of your name with the name of current and previous employers.
1. Conduct a Google search of your name with the name of previous schools you attended.
1. Expand your search to include social media sites, for example: “snow white” twitter; “snow white” facebook; “snow white” youtube etc.
1. Note any interesting or surprising findings.

```

### Activity: Blog: My Digital Footprint {-}

```{block2, type='reflect'}

Prepare and publish a short blog post of about 250 to 300 words focusing on what you hope to achieve with your online digital identity for learning. Your post can include:

1. Optional reflection: You may want to include a reflection(s) on the outcomes of your footprint audit. Remember that your blog post is public, so only share what you are comfortable sharing with the world. You don’t need to be specific; for example, you can generalise: I am satisfied with my digital footprint because … or I would like to improve my digital footprint for learning because …

1. Professional versus private: Consider how you want to separate your “private” online identity from your professional and / or learning identity. If you already maintain an online presence (existing blog, twitter and/or facebook accounts) think about how you will separate professional / learning posts from private and social life interactions online. For example, maintaining a separate course or learning blog is one way to achieve this distinction. Will you link your personal online identities (e.g.an existing Twitter username or Facebook account) with your learning blog? Will you link your professional online identity (e.g. published online biography on your employer’s web site) with your learning blog?

1. Objectives: List a few objectives for developing or improving your online identity.

1. Remember to add a category or tag to your post using the course tag: LDRS101 (This is needed to harvest links to posts from registered course blogs for the course feed.)

Remember: You are in charge of what you post online and deciding what you would like to share for your digital identity for the purposes of this course. Don’t share high risk personal details like physical address, date of birth, name of first pet etc., which may make it easier for identity thieves to appear more credible. If unsure, consult online resources for internet safety; for example Netsafe New Zealand. (replace resource)

!! Note that we will cover online identity in more depth in Unit 5.

```

### Activity: Blog: My Online Biography {-}

```{block2, type='reflect'}

In this challenge you are asked to build or update your professional online biography and the “About” page of your course blog. 

1. Reflect on the following online personas, target audience and how this will impact on the style and voice of the communication medium.  

| **Persona**  | **Primary audience**               |
|--------------|------------------------------------|
| Personal     | Friends and family                 |
| Professional | Employers and professional network |
| Academic     | Peer learning network              |


2. Choose the most appropriate medium for each of your online personas, for example:    
| **Persona**  | **Medium example**                    |
|--------------|---------------------------------------|
| Personal     | [Facebook](https://www.facebook.com/) |
| Professional | [Linkedin](https://www.linkedin.com/) |
| Academic     | Course blog or website                |


3. Identify one or two professionals from your field of interest who maintain an active web presence and contribute regularly via social media. Explore their respective websites and professional listings as examples.  
- Twitter is a good place to search for individuals using popular hashtags from your field or area of study, for example “#highereducation”  
- Click through to their respective twitter user page. If they have a personal website listed on the user page, visit the site and review their “About” page.  
- Visit their employer’s page and try to locate their biography on the employer’s website.  
- Search for the user on Linkedin  
- Compare the user information on these different sites. Observe how they link to social media accounts, and vary the style and content presented for the different personas.

4. Create or update your professional profile on Linkedin. (Consult the help page for support.)  

5. Create or update your “About” page on your course blog. You may prefer using a more informal style for this page aligned with your own personality and interests. Include links to your professional profile and respective links to social media that you use.

6. Visit the profile pages of your active social media accounts. Update if necessary providing links back to your main page (for example, the “About” page on your course site).

7. Think carefully about information you post publicly and keep a clear distinction between your personal online presence and your professional online persona. Review your privacy settings on your personal account(s).

```

## Evaluating Online Tools

In this topic, we invite you to think critically about the tools you use online.  More than the obvious questions about whether the tool works well, is easy to navigate, etc., how do we evaluate digital tools, platforms, and interactions based on *ethical principles*?

...


Improve your skills in becoming a critical consumer of web tools
Publish a critical product review for an online tool of your choice.

<!--
Bringing it Home!

Connect - where students have been - what their online idenity is/was/want to be = and what tools they've used/are using/want to use.  
What do you want to do online?  What do you want to learn? What are your goals?  

Inquiry-based.
Practicing evaluative judgment 


Course Learning Outcomes related to this unit: 
- Practice evaluative judgment to document your process of learning in complex domains of knowledge
- Create a personalized narrative to document and express your learning process
- Evaluate digital tools, platforms, and interactions based on ethical principles
-->

<!--
comment
-->



### Activity:  {-}

```{block2, type='reflect'}

Read the following articles about ...


https://www.internetsociety.org/policybriefs/privacy/

https://ethicaledtech.info/wiki/Meta:About


[How to write a product review](https://www.wikihow.com/Write-a-Product-Review)
[Terms of service. Didn’t read](https://tosdr.org/)

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```



### Activity:  {-}

```{block2, type='reflect'}


In this challenge, you are invited to critically evaluate an online tool. Please select any online tool, or choose one from the list below.
 
Examples of software as service

- Blogging: Blogger, WordPress, Medium, Tumblr
- File sharing: Dropbox, Nextcloud, MediaFire, Google Drive, SugarSync
- Presentations: Haikudeck, Prezi, Google Slides, Slides (using Reveal.js)
- Online collaboration: Basecamp, Slack, Rocket.chat, Hipchat
- Video conferencing: jitsi, Anymeeting, Zoom, GoToMeeting
- Feed aggregators: Feedly, Panada, NewsBlur, Inoreader, Feedreader.
- Project management: Trello, Kanboard, Freedcamp, Asana, Notion, GitHub

What tool did you select? Let us know by posting a comment on Discourse sharing the name of the tool you selected and why.

Note: Your comment will be displayed in the course feed.

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```


## Summary {-}

In this unit, you have had the opportunity to learn about ...



## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Digital Literacy Portfolio</span>

The learning activities in this unit were designed to support you as you build your *Digital Literacy Portfolio*.  

Your portfolio will demonstrate how you apply digital tools to support your learning.  It measures the following course learning outcomes:  
- Create a personalized narrative to document and express your learning process  
- Evaluate digital tools, platforms, and interactions based on ethical principles  
- Practice evaluative judgment to document your process of learning in complex domains of knowledge  

**Performance Indicators**  
*I can do the following:*  
- Maintain a public personal blog as my elearning portfolio.  
- Interact constructively with public online learning communities using forums and social media.  
- Annotate and discuss web resources publicly in support of my learning.  
- Share with my learning peer group recommendations for online resources that I have found to be useful.  
- Use citation management software for my personal online resource library.  

See the Assessment section in Moodle for instructions, including the grading rubric.

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- ...
- ...
 

```
