# Building a Network of People


## Overview {-}

In Unit 5 we engage in academic learning as a digital citizen of the internet. In this unit you will continue to develop a positive digital online identity in support of learning while adhering to best practices for privacy, security and interpersonal communications.


### Topics {-}

This unit is divided into the following topics:

1. Digital Citizenship
2. Online Communities
3. Digital Practices in Academia & the Workplace
4. Communities of Practice

  

### Learning Outcomes {-}

When you have completed this unit, you should be able to: 

- Discuss the dimensions of digital citizenship for work and learning in the 21st century and how these differ from the off-line environment  
- Outline the rights and responsibilities of a digital citizen  
- Apply good online hygiene practices to ensure your privacy and security in digital environments  
- Evaluate a range of social media, technologies and communities appropriate for supporting learning  
- Gain an understanding of the implications of digital technology for your future career  
- Develop online learning networks to discover and share knowledge, collaborate with others, and become engaged digital global citizens  
- Describe societal issues and problematic online behaviours which have emerged in the digital world and how to deal with these challenges in an ethical manner  




### Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.


```{block2, type='reflect'}

<span class="blockhead">Learning Activities</span>

- ...
- ...
 
**Note:** The learning activities in this course are designed to prepare you for the graded assigments in this course.  You are strongly encouraged to complete them.


```

```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

- **Digital Citizenship Blog**
- **Digital Literacy Portfolio** 
See the Assessment section in Moodle for assignment details and due dates.

```



### Resources {-}

- All resources will be provided online in the unit.  

```{block, type='feedback'}

***Resource Reminders***  
- Don't forget to add resources to your Zotero library that align with your individual learning path.  
- Remember, your fellow students are a valuable resource! Engage with your online community for assistance, and don't hesitate to exchange helpful resources and valuable insights.  

```


## Digital Citizenship

Before attempting to define *digital citizenship*, let's consider the concept of citizenship in its own right. In its simplest form, citizenship refers to the rights, privileges and duties of being a national citizen. However, the concept of being a good citizen encompasses much more, particularly if you think about full engagement as a member of society.  

>“Citizenship is a status that is bestowed on those who are full members of a community.”  
>—T.H. Marshall




### Activity: Reflecting on Digital Citizenship {-}

```{block2, type='reflect'}


If good citizenship means to fulfill your role as citizen, can you think of five things good citizens do? Consider the following questions:

- In a digital world, is loyalty to your country a necessary component of the definition of good citizenship?  
- Is education a pre-requisite for good citizenship?  
- In a digital world, what does it mean to be a global citizen? Read the Wikipedia article on [Global Citizenship Education](https://en.wikipedia.org/wiki/Global_citizenship_education) where learners engage in solving real world problems.  
-  Has the concept of good citizenship changed over time? In what ways?  
- Does citizenship require active community engagement? Read this post by Kristen Mattson, director of a high school library media center: [John Dewey Would Hate Your Digital Citizenship Curriculum](https://drkmattson.wordpress.com/2016/08/03/john-dewey-would-hate-your-digital-citizenship-curriculum/).  
- Why has the concept *digital* been linked with *citizenship* or should we drop the word *digital* and just talk about *good citizenship*?  

Write your thoughts in your Reflective Journal (using Obsidian or WordPress).

Conclude by writing down a description of “digital citizenship” in your own words. (You will need this later for the assessment. It does not need to be a scholarly definition – just your personal thoughts on the concept.)

```

### Defining Digital Citizenship {-}

Defining digital citizenship is not easy because it means different things to different people. It is also a concept which is debated among scholars researching the field.  

If you conduct a general search for “digital citizenship” you will find many links referencing resources targeting the school-level, with a focus on safe, skilled and ethical use of online technology. While these aspects are important, for the purposes of this tertiary-level course, we need to explore the concept of digital citizenship in more detail.  


### Activity: Podcast on Digital Citizenship {-}

```{block2, type='reflect'}

In this activity you will listen to a podcast that focuses on the people dimension of digital citizenship.

Meet [Autumm Caines](http://autummcaines.com/), associate director of academic technology from the Center for Excellence in Learning and Teaching at Capital University in a podcast with Bonni Stachowiak.

Listen to the first 15–20 minutes of this Teaching in HigherEd podcast on Digital citizenship. The podcast introduces aspects of digital citizenship and the learner experience in starting out with engagement with social media.


<iframe title="Digital Citizenship" allowtransparency="true" height="150" width="100%" style="border: none; min-width: min(100%, 430px);" scrolling="no" data-name="pb-iframe-player" src="https://www.https://content.blubrry.com/teaching_in_higher_ed_faculty/tihe115.mp3"></iframe>



```

### Activity: Refined Definition of Digital Citizenship {-}

```{block2, type='reflect'}

The purpose of this activity is to explore the elements of digital citizenship with particular emphasis on those relevant to your academic study.  

Read through the following resources in order to refine your own definition of what it means to be a Digital Citizen.

**Step 1: Online Search:**  
- Read the introductory section of the Wikipedia article: [Digital citizen](https://en.wikipedia.org/wiki/Digital_citizen)  
- Conduct a general search for “definition of digital citizen.” Choose the two best definitions and add these to the library of your citation management tool (Hypothes.is / Zotero / Obsidian), or keep a record for citation purposes.  
- Try and locate one recent scholarly definition for “digital citizen.” Record the reference for citation purposes. How recent is the reference?  

**Step 2: Social Media Search:** 
- Explore the recent tweets (on X or whichever social media app you prefer) using the following hashtags: #digitalcitizenship, #digiciz, and #digicit.  Compile a list of elements relating to the concept of digital citizenship.  

**Step 3: Read & Comment:** 
- Login to hypothes.is.  
- Read [Nine elements of digital citizenship](https://www.digitalcitizenship.net/nine-elements.html) by Mike Ribble  
- Feel free to add or reply to annotations using Hypothes.is. Remember to tag your posts using the course code: #LDRS101 (This is needed to harvest posts for the course feed.)  


**Step 4: Apply the Elements** 
Generate a table listing the nine elements of digital citizenship and identify a practical example of the element for your academic study: For example:  

| **Element**  | **Academic Study Example**               |
|--------------|------------------------------------|
| Digital access     | Students from low income countries may not have reliable or affordable access to the Internet.                 |
| Digital commerce  |  |
| Digital communication     |               |
| Digital literacy     |                  |
| Digital etiquette  |  |
| Digital law      |              |
| Digital rights and responsibilities     |                  |
| Digital health and wellness |  |
| Digital security       |               |
	  
  
**Step 5: Define Digital Citizenship**
After completing the steps above, revise your personal description of digital citizenship. Does your new definition differ from your initial description?  

**Step 6: Share Your Insights!**
Share a reflection on this activiy by posting either in your blog or on the Discourse forum.

For example:

- I didn’t realize the ... is part of digital citizenship because …  
- ... is not particularly relevant for university learners because …  
- ... is particularly relevant for university learners because …  

```



### Rights and Responsibilities {-}
The concept of citizenship encompasses the rights and responsibilities of individuals. We need to consider what rights and responsibilities come with digital citizenship. In this mini challenge, we explore this topic with particular emphasis on the rights and responsibilities associated with learning in a digital age.

Following the hype of massive open online courses (MOOC) and the New York Times declaring 2012 the “[year of the MOOC](https://www.nytimes.com/2012/11/04/education/edlife/massive-open-online-courses-are-multiplying-at-a-rapid-pace.html),“ a small group of educators drafted “A Bill of Rights and Principles for Learning in a Digital Age.” This document forms the basis for a course discussion on the rights and responsibilities of digital citizens.



### Activity: Rights & Responsibilities of Digital Citizens {-}

```{block2, type='reflect'}

1. **Search:** Conduct a general search for rights and responsibilities of digital citizenship to assist in refining your own list for university online study. Your search is likely to generate many results developed for the school sector, so you need to evaluate if these rights and responsibilities are appropriate for you.  

- Udacity version of the bill of rights: [A Bill of Rights and Principles for Learning in the Digital Age](https://www.udacity.com/blog/2013/01/a-bill-of-rights-and-principles-for.html)
- [‘Bill of Rights’ Seeks to Protect Students’ Interests as Online Learning Rapidly Expands](https://www.chronicle.com/article/bill-of-rights-seeks-to-protect-students-interests-as-online-learning-rapidly-expands/), from the Chronicle of Higher Education.  
- [Critique of ‘Bill of Rights and Principles for Learning in the Digital Age’](https://www.insidehighered.com/blogs/law-policy-and-it/critique-bill-rights-and-principles-learning-digital-age) from Inside Higher Ed.  

Conduct a search through the TWU library for [Digital Rights and Responsibilities](https://twu.idm.oclc.org/login?url=https://search.ebscohost.com/login.aspx?direct=true&bquery=digital+rights+and+responsibility&cli0=FT1&clv0=Y&type=0&searchMode=And&site=eds-live&scope=site)

Remember to annotate and comment on the Hypothes.is and tag your contributions using the course code: #LDRS399  

2. **Blog:**  Prepare a table summarising the primary rights and responsibilities for university learning in a digital age.  

3. **Discuss:**Drawing on your knowledge and experience, please join the discussion on Discourse regarding rights and responsibilities for learning in a digital age at TWU. You can discuss the topical issues listed below, or add new ones to the forum. In each case, justify your position taking opposing views into account.  

*Topical Issues*:

- Should higher education institutions have the right to determine what software applications learners should use for their studies?  
- Data generated by learners belongs to the learners, therefore should they have the right to access their data (for example forum discussion contributions) even after the course has completed?   
- Should higher education institutions reserve the right to ban disruptive learners from their learning platforms?  
- Where legally permissible, should learners have the right to access all course materials without the need to register a password?  
- Should higher education institutions have the right to limit the time required for completing a course?  
- Others?  

We encourage learners to reply and “like” good posts. (Remember to tag your posts using the course code: LDRS101).  

```

## Online Communities 

In this section we explore the topic of online communities and how we can engage in social media to enhance our learning.

In the early years of the internet, there was a strong research interest in studying the differences between virtual and real communities. However, in more recent years, we have observed a blurring of the boundaries between online and real communities. In [The difference between online & real life community?](https://quiip.com.au/is-there-a-definitive-difference-between-online-and-real-life-community/) Alison Michalk states:

> Community boundaries are blurred to the extent that the Internet is nothing more than a conduit for communication. The Internet is now just another tool that we use to communicate within our various communities. The same as we use mail, telephone and even a car to keep in touch with our friends, family and colleagues. Our ‘real life communities’ are not mutually exclusive from our ‘online communities’ given that it all comes down to implied physical presence. (2013, June 27)

So how do we join and contribute constructively to these digital communities? If you don’t have much experience with online communities, we enccourage you to participate in the course forums and become an active member of the TWU online learning family.



### Activity: What's My Network? {-}

```{block2, type='reflect'}

Online communities are varied and can be categorized by their purpose: social, academic, professional, etc.  For this activity, we encourage you to consider what your purpose is in building an online community.  
- Do you want to connect with TWU peers internationally and in Canada?  Is your focus on academic support, or building personal relationships?  
- Are you interested in the communities that relate to your chosen profession?  If so, do a quick search for online communities for a career that interests you (see example for businesses: [15 Best Online Community Platforms of 2023 (Ranked)](https://www.mightynetworks.com/resources/community-platforms).   
- Do you want to engage with online communities that align with your personal interests? (e.g. sports, arts, politics, gardening, coding, etc.)  

Write down your goals for joining an online community.

```



### Activity: Identity, Social Media, and Learning {-}

```{block2, type='reflect'}

 In this activity we will explore how social media can support online learning and implications for engagement and identity.  
 
Read: Using Social Media for Learning. A guide to Becoming Strategic from Sheffield Hallam University.  
Explore: The Conversation Prism developed by Brian Solis.  
Reflect on the social media technologies you use for learning and how this impacts on your digital footprint and online identity.
Annotation - Learners on the Periphery  
Read the following article and add or reply to annotations using Hypothes.is focusing on how the research might apply to your own behavior. Remember to tag your posts using the course code: lida102  

Honeychurch, S., Bozkurt, A., Singh, L., & Koutropoulos, A. (2017). Learners on the Periphery: Lurkers as Invisible Learners. European Journal of Open, Distance and E-Learning, 20(1).  
Frameworks for Online Engagement  
Read Derek Wenmouth’s blog post: Participation online – Four C’s. How does this apply to your own online engagement?  
Watch the following video based on Ross Mayfield’s Power Law of Participation. Note how low threshold engagement on social media leaves a bread crumb (digital footprint) and generates a form of collective intelligence. Higher forms of engagement result in collaborative intelligence. Note that Cheryl Reynolds refers to Yammer in the video, but the framework also applies to other social media platforms.   While you watch the video, think about how you engage in different online communities.  



Forum – Social Media, Online Identity, and Learning  
Join the discussion on social media, online identity and learning by sharing your personal views and thoughts. Choose one or more of the following questions as a catalyst for your contributions to the forum:  

How much of what you learn should be open and transparent (i.e. public) and how much should be kept private? Why?  
In a digital age, how important is it for you to build a digital footprint of your learning?  
What are the challenges and opportunities for building your online identity?  
What levels of online engagement do your feel are appropriate for your own learning on this course? Does this differ from your engagement in other online communities?  
Other?  
Please “like”, share and reply to posts. These are forms of engagement and a contribution to your online learning identity. Remember to tag your posts using the course code: lida102  

```



### Activity: ... {-}

```{block2, type='reflect'}

Social media for learning

Exploring how social media can support online learning and implications for engagement and identity

The purpose of this mini challenge is to:

Review social media technologies and how they can support or inhibit learning in a digital age.  
Reflect on engagement in online communities.  
Consider the relationship between sharing learning online and your digital footprint and online identity.  

---

Annotation - Learners on the periphery

Read: Using social media for learning. A guide to becoming strategic published by Sheffield Hallam University.  
Explore: The conversation prism developed by Brian Solis.  
Reflect on what social media technologies you use for learning and how this impacts on your digital footprint and online identity.  
Share what social media technologies you use to support learning and how you use them by posting a WENote, for example:  

I use <insert tool> to <describe purpose and how it supports your learning>  
In the future, I plan to use <insert tool> to <describe purpose and how it will support your learning>  

---

Frameworks for online engagement

Read the following article and add or reply to annotations using  on the  Hypothes.is focusing on how the research might apply to your own behaviour. Remember to tag your posts using the course code: LiDA102. (Consult the OERu support site for help on using the Hypothes.is annotation tool.)

Honeychurch, S., Bozkurt, A., Singh, L., & Koutropoulos, A. (2017). Learners on the Periphery: Lurkers as Invisible Learners. European Journal of Open, Distance and E-Learning, 20(1). (Direct hypothes.is link.)

Read Derek Wenmouth’s blog post: Participation online – Four C’s (How does this apply to your own online engagement?).
Watch the following video based on Ross Mayfield’s power law of participation. Note how low threshold engagement on social media leaves a bread crumb (digital footprint) and generates a form of collective intelligence. Higher forms of engagement result in collaborative intelligence (note that Cheryl Reynolds refers to Yammer in the video, but the framework also applies to other social media platforms). When viewing the video, think about how you engage in different online communities.



<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/WBjSTurfu3k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


Forum - Social media, online identity and learning

Join the discussion on social media, online identity and learning by sharing your personal views and thoughts. Choose one or more of the following questions as a catalyst for your contributions to the forum:

How much of what you learn should be open and transparent (i.e. public) and how much should be kept private? Why?  
In a digital age, how important is it for you to build a digital footprint of your learning?  
What are the challenges and opportunities for building your online identity?  
What levels of online engagement do your feel are appropriate for your own learning on this course? Does this differ from your engagement in other online communities?  
Other?
Please “Like”, share and reply to posts. These are forms of engagement and a contribution to your online learning identity. Remember to tag your posts using the course code: LiDA102.  

```



## Digital Practices in Academia and the Workplace  

In this topic we consider how changes in technology will impact on digital practices in the workplace.

Describe how like-minded professionals in your field of interest network online.
Discuss how technology has changed business practices in your field of interest or career.
List contemporary examples of artificial intelligence in the workplace.
Review the potential impact of automation in your field of interest or career.
List the implications for learning and skills development in your future career precipitated by changes in digital technology.

### Activity: The Future of Work (Optional) {-}


```{block2, type='reflect'}

In this short video signpost, [Ken Steele](http://eduvation.ca/bio/) from Eduvation speculates about the future of the labour market and the value of higher education in a digital age.

Watch [Higher Ed Trends: Student Career Anxiety and the Future of Work](https://www.youtube.com/watch?v=iY4UhfQefdU)


<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/iY4UhfQefdU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


What do you think? Share your thoughts by posting a comment on Discourse, for example:

Higher ed is valuable because …
- In a digital age …
- I am confident that …
- I am concerned about …

```



### Personal and Professional Identity {-}

In short, digital citizenship is about being a person on the web. In the previous unit on building your online presence, we noted that individuals portray different personas online, for example personal, academic and professional.

On the one hand, we need to be careful about what we post online because this can have a negative impact on future career prospects or current employment. We must also be cognisant of the different limitations that different careers place on what can be shared publicly and what needs to stay private. On the other hand, building a strong learning or professional network online is very powerful in staying up to date with new trends and establishing connections with your peers.

In this section, we reflect on the balance between public and private in a digital world, recognising that this is going to be different for each person depending on their own environments and professional circumstances. We will also explore how like-minded professionals in your field of interest network online.


> “The impact exercised by ICTs is due to at least four major transformations: the blurring of the distinction between reality and virtuality; the blurring of the distinction between human, machine and nature; the reversal from information scarcity to information abundance; and the shift from the primacy of stand-alone things, properties, and binary relations, to the primacy of interactions, processes and networks." —Luciano Floridi

### Activity: Professional Online Identity and Digital Citizenship {-}

```{block2, type='reflect'}

In this activity we will explore professional online identity and networking in the field of your choice.  

First, scan a few of the following resources:

- [High court rules public servants can be sacked for political social media posts](https://www.theguardian.com/australia-news/2019/aug/07/high-court-rules-public-servants-can-be-sacked-for-political-social-media-posts), published by The Guardian.  
- [‘Think of social media as a virtual resumé](https://www.cbc.ca/news/canada/saskatoon/experts-surprised-by-what-people-will-say-on-social-media-1.4176138),’ expert warns in light of health board resignation, published by CBC News.  
- You can also search online using the terms "fired over tweet" or "social media firing cases".


Next, watch this short video interview with Alec Couros, published by Teaching and Learning in South Australia. Alec summarises how educators are using twitter to connect professionally. 
[Using Twitter effectively in education - with Alec Couros](https://www.youtube.com/watch?v=EqSCR3HU4eg)


<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/EqSCR3HU4eg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


Finally, visit the LinkedIn help page on [finding and joining a LinkedIn group](https://www.linkedin.com/help/linkedin/answer/a544795).

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- How do like-minded professionals in your career or future career, field, discipline etc. network online (for example X, LinkEdIn groups, other websites?)? 
- What hashtags, if any, are being used for conversations in your chosen field? 
- What are the topical areas of discussion at the moment? 
- How could your field of interest improve professional networking online? 
- Do organisations in your field place restrictions on employees participating in social networks? (See for example [Corporate Social Media Policies: The Good, the Mediocre, and the Ugly](https://www.fastcompany.com/1668368/corporate-social-media-policies-good-mediocre-and-ugly), and [More Social Media Policies: LA Times, Harvard Law, Microsoft, and Cisco](https://www.fastcompany.com/1670530/more-social-media-policies-la-times-harvard-law-microsoft-and-cisco).) 

```

### Activity: Blog: Professional online identity and digital citizenship (Optional) {-}

```{block2, type='reflect'}

Prepare a short blog post (about 300 – 400 words) summarising your findings on professional online networking in your field of interest. Consider the following questions:

- How do like-minded professionals in your field network online and what do they talk about?  
- What does this mean for your online identity and being a digital citizen?  

Remember to add a category or tag for your post using the course tag: LDRS101.

```

### Activity: Blog: My Online Biography (Optional) {-}

```{block2, type='reflect'}

In this challenge you are asked to build or update your professional online biography and the “About” page of your course blog. 

1. Reflect on the following online personas, target audience and how this will impact on the style and voice of the communication medium.  

| **Persona**  | **Primary audience**               |
|--------------|------------------------------------|
| Personal     | Friends and family                 |
| Professional | (Future) Employers and professional network |
| Academic     | Peer learning network              |


2. Choose the most appropriate medium for each of your online personas, for example:    

| **Persona**  | **Medium example**                    |
|--------------|---------------------------------------|
| Personal     | [Facebook](https://www.facebook.com/) |
| Professional | [Linkedin](https://www.linkedin.com/) |
| Academic     | Learning blog or website                |


3. Identify one or two professionals from your field of interest who maintain an active web presence and contribute regularly via social media. Explore their respective websites and professional listings as examples.   
- X (formerly Twitter) is a good place to search for individuals using popular hashtags from your field or area of study, for example “#highereducation”.    
- Click through to their respective X user page. If they have a personal website listed on the user page, visit the site and review their “About” page.  
- Visit their employer’s page and try to locate their biography on the employer’s website.  
- Search for the user on Linkedin  
- Compare the user information on these different sites. Observe how they link to social media accounts, and vary the style and content presented for the different personas.

4. Create or update your professional profile on Linkedin. 
- Consult TWU's [Student Resources website](Student Resources
) about LinkedIn.) TWU gives you access to LinkedIn Learning, which includes several great courses and videos, such as [Rock Your LinkedIn Profile](https://www.linkedin.com/learning/rock-your-linkedin-profile/connect-to-opportunity-with-linkedin?u=124451074). 

5. Create or update your “About” page on your Learning Blog. You may prefer using a more informal style for this page aligned with your own personality and interests. Include links to your professional profile and respective links to social media that you use.

6. Visit the profile pages of your active social media accounts. Update if necessary providing links back to your main page (for example, the “About” page on your website).

7. Think carefully about information you post publicly and keep a clear distinction between your personal online presence and your professional online persona. Review your privacy settings on your personal account(s).

```

### Technology and Change {-}

Throughout history, there are technologies which have influenced change in society. Consider for example, the invention of the steam engine and its contribution to the Industrial Revolution. In more recent times, the advent of digital photography displaced Kodachrome (at one time, the market leader in colour film sales) which ceased production in 2009.

### Activity: Annotation - Newspaper and music industry in a digital age  {-}

```{block2, type='reflect'}

The readings which follow take a retrospective look at the impact of the Internet on the newspaper and music industries.

Please add or reply to annotations using [Hypothes.is](https://web.hypothes.is/) sharing personal insights and experiences. Remember to tag your posts using the course code: LDRS 101. 

1. Read [Chapter 3](https://www.bloomsburycollections.com/monograph-detail?docid=b-9781849666275&tocid=b-9781849666275-chapter3) of Weller, M. (2011). [The Digital Scholar: How Technology is Changing Academic Practice](https://www.bloomsburycollections.com/monograph?docid=b-9781849666275). Bloomsbury Publishing PLC. (Direct [hypothes.is link](https://via.hypothes.is/https://www.bloomsburycollections.com/monograph-detail?docid=b-9781849666275&tocid=b-9781849666275-chapter3).)  
2. Read: [How streaming saved the music industry](https://www.theguardian.com/music/2018/apr/24/weve-got-more-money-swirling-around-how-streaming-saved-the-music-industry), published by the Guardian. (Direct [hypothes.is link](https://via.hypothes.is/https://www.theguardian.com/music/2018/apr/24/weve-got-more-money-swirling-around-how-streaming-saved-the-music-industry).)  
3. Read: [The future of newspapers in the digital age](https://medium.com/international-online-journalism/the-future-of-newspapers-in-the-digital-age-c7ac8a118312), published by Julien Sueres. (Direct [hypothes.is link](https://via.hypothes.is/https://medium.com/international-online-journalism/the-future-of-newspapers-in-the-digital-age-c7ac8a118312).)  

```


### Activity: Impact of digital technology on business {-}

```{block2, type='reflect'}

Join the discussion on the impact of digital technology on business:

1. Choose any business or work environment (for example, your current career or future career)  
2.  Think about examples of how digital technology has had an impact on your chosen business over the last 30 years.  
3. State your business or work environment and share a practical example of how digital technology has influenced change in your chosen area:  
    - Has the example contributed to a fundamental change in the way things were done, or is this a minor change?  
- Do you anticipate significant changes in your industry as a result of digital technology in the future? Provide an example.  

Please “Like”, share and reply to posts. These are forms of engagement and a contribution to your online learning identity. Remember to tag your posts using the course code: LDRS101.

```

### Artificial intelligence {-}

Artificial intelligence (AI) is predicted to have a significant impact on society and business. Examples include, autonomous cars, computers understanding human speech and machine learning. Consider for instance, that computer chess games available for commercial desktop machines have the ability to beat accomplished chess players including grand masters.  And of course, Chat GPT.  

In this section we introduce a few interesting examples of artificial intelligence to provide a sense of how sophisticated these technologies are becoming.

First, let's define AI:

> "The theory and development of computer systems able to perform tasks normally requiring human intelligence, such as visual perception, speech recognition, decision-making, and translation between languages" ([Oxford Reference](https://www.oxfordreference.com/display/10.1093/oi/authority.20110803095426960))

> "The capacity of a computer to perform operations analogous to learning and decision making in humans, as by an expert system, a program for CAD or CAM, or a program for the perception and recognition of shapes in computer vision systems" ([Dictionary.com](https://www.dictionary.com/browse/artificial-intelligence))

What is your experience with AI?  Have you used an AI tool, such as Grammerly or ChatGPT? How has this technology affected you as a student, and what effect do you think it has/will have on your chosen profession?  

In the next activity, we'll explore some of these questions and concerns.


### Activity: How Can I Use AI? {-}

```{block2, type='reflect'}

First, do a quick search online for AI tools for university students. 
Examples:
- [How can AI be used by university students?](https://www.timeshighereducation.com/student/advice/how-can-ai-be-used-university-students)- [The 10 Best AI Tools to Help Students Learn Faster](https://mystudylife.com/10-best-ai-tools-to-help-students-learn-faster/))

Intrigued? Do you find any tech tools that you might use to help you with understanding course topics, studying, generating flashcards, transcribing lectures and voice notes, grammar, writing an essay, creating a slideshow presentation, drafting a forum discussion post, etc.?

Do any of these capabilites concern you?  Do you think they concern your professors or fellow students? 

Review TWU's policy on [Academic Misconduct & Fraud](https://www.twu.ca/about-us/policies-guidelines/university-policies/academic-misconduct-fraud).

Search online for key words related to this issue, such as "university concern policy artificial intelligence" and you will find numerous articles on the use of AI in universities, as well as emerging policies.  (e.g. University of Toronto's guidelines for [ChatGPT and Generative AI in the Classroom](https://www.viceprovostundergrad.utoronto.ca/strategic-priorities/digital-learning/special-initiative-artificial-intelligence/)

Switch your perspective to your chosen field.  How can AI benefit your industry?  Are there any concerns regarding how AI might be used?

Share you thoughts on AI by posting a comment on Discourse, for example:

- AI will …  
- I was surprised that AI …  
- In <insert business> AI will …  

```

### Jobs and automation {-}

In this section we consider the impact of automation on the future job market and the implications for education and training.

- Will robots replace humans?  
- What jobs are most at risk of being replaced by robots?  
- What are the implications for learning in a digital age?  



### Activity: Impact of automation on the labour market {-}


Watch [Humans Need Not Apply](https://www.youtube.com/watch?v=7Pq-S557XQU)



<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/7Pq-S557XQU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>



### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```




## Communities of Practice

In this unit, you have considered the learning networks you want to join, perhaps as a university student, or in your chosen profession. Our final topic for this unit centres around building a Community of Practice. 

> A community of practice (CoP) is a group of people who "share a concern or a passion for something they do and learn how to do it better as they interact regularly". Wenger, 2014 

Cognitive anthropologists Jean Lave and Etienne Wenger coined the term “community of practice” when studying apprenticeships as a learning model—the term referred to the community that acts as a living curriculum. Once the concept was articulated the researchers started to see communities everywhere, even when no formal apprenticeship system existed.

The basic premise behind communities of practice is simple: we all learn in everyday life from the communities in which we find ourselves. Communities of practice are everywhere. Nearly everyone belongs to some community of practice, whether it is through our working colleagues or associates, our profession or trade, or our leisure interests, such as a book club. Wenger (2000) argues that a community of practice is different from a community of interest or a geographical community in that it involves a shared practice: ways of doing things that are shared to some significant extent among members.

#### Characteristics of A Community of Practice {-}

Wenger argues that there are three crucial characteristics of a community of practice:

1. **Domain:** A common interest that connects and holds together the community;
2. **Community:** A community is bound by the shared activities they pursue (for example, meetings, discussions) around their common domain;  
3. **Practice:** Members of a community of practice are practitioners; what they do informs their participation in the community; and what they learn from the community affects what they do.

Wenger (2000) has argued that although individuals learn through participation in a community of practice, more important is the generation of newer or deeper levels of knowledge through the sum of the group activity. If the community of practice is centered around business processes, for instance, this can be of considerable benefit to an organization. 

#### Types of Communities of Practice {-}
Today, communities of practices are increasingly being used to improve knowledge management and connect people within business, government, education, and other organizations.

The design of the community will look different depending on the purpose and needs of the participants. There are four basic types of communities:

1. **Helping Communities** provide a forum for community members to help each other with everyday work needs.

2. **Best Practice Communities** develop and disseminate best practices, guidelines, and strategies for their members’ use.

3. **Knowledge Stewarding Communities** organize, manage, and steward a body of knowledge from which community members can draw.

4. **Innovation Communities** create breakthrough ideas, new knowledge, and new practices.

As you reflect on digital practices in university and the workplace, consider how engaging in a Community of Practice could benefit you as a learner and in your future career.  


### Activity: What Is a Community of Practice? {-}

```{block2, type='reflect'}

Watch the video, [Communities of Practice (Etienne and Beverly Wenger-Trayner)](https://www.youtube.com/watch?v=SmqLyOLIjos)

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/SmqLyOLIjos" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

To learn more about the origins and theory of communities of practice, see [Introduction to communities of practice](http://wenger-trayner.com/introduction-to-communities-of-practice). 

Feel free to discuss your topics of interest in TWU Discourse, or search online for CoPs that interest you.

```



## Summary {-}

In this unit, you have had the opportunity to learn about ...



## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Digital Citizenship Challenge</span>

After completing this unit, including the learning activities, you are asked to prepare a learning reflection based on the knowledge you have gained on the concept of digital citizenship. 

This learning challenge is based on the learning activities in this unit. You are encouraged to complete this assignment on your blog.  Note that you can control the privacy settings of each post (e.g. only you can see it > only your instructor > your TWU peers > open to all who come across it on the web!). 

In your Reflective post, provide the following:  
- your personal description of digital citizenship;  
- your revised definition of digital citizenship based on your research of the topic;  
- list of university-level study examples of the elements of digital citizenship;  
- a summary of the primary rights and responsibilities for learning in a digital age;  

Resources: 
- video on [How to Write a Reflection Essay](https://www.youtube.com/watch?v=Fk2GjRIRBIk) by Melissa Wehler

In addition to the tasks above, prepare a learning reflection of about 500–600 words reflecting on the development of your understanding of digital citizenship.

Your post should cover the following aspects:

**Description**: Provide your reader with specifically what happened?  
**Evaluation**: What was “good” and “bad” about the experience?  
**Analysis**: What did you learn from it? How do you feel about it now? Did it change you? How?  
**Conclusion**: What alternatives did you have at the time or what else could you have done?  
**Plan**: What new knowledge or skills do you have and how will your experience inform future learning?  


Add a category or tag for your post using the course tag: ldrs399.  
See how to add a tag in WordPress or in Blogger see Change settings on your posts to add a label.  
The tag is needed for the harvester we use to identify posts for the LiDA course. If the tag is missing, we will not be able to incorporate your post into the course feed. This is done automatically once you have registered your blog url on the course site (see below).  
You will need to register the full url for the PUBLIC view of your blog site. We need this url to harvest posts tagged or labelled with hash tag “lida102” for the aggregated course feed. Please note that it may take up to an hour before your posts appear in the feed due. If the post does not appear in the feed after a few hours, check that you registered the correct url for the published view and tagged / labelled your post using the course code.  
To register your blog url, click on the user icon in the site menu above. If you’re logged in, use the update button to enter the full url of the PUBLIC view of your blog. (Tip: Don’t use the dashboard url used for editing your blog).  
Post a comment on one or two blog contributions.  


```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- ...
- ...
 

```

