# Sharing Your Knowledge

## Overview {-}

Congratulations! You've made it to the final unit in our course, Learning with Technology.  In this last unit we will have a chance to explore some digital tools that you may encounter in your academic studies at TWU.  We'll look at how these skills translate to preparing you for the workplace, and will examine the role technology plays in your chosen field of study.  You'll also have the opportunities to research some current events related to societal issues and the internet, and will discuss how to address these challenges.  Finally, we'll conclude our course with a discussion on digital wisdom.  As you begin this unit, here are some guiding question to consider:

> "How will my use of technology support my social, academic, and spiritual goals?"   
> "How will I share my knowledge and skills to engage as a digital global citizen?"  
> "How will I connect and collaborate with others as part of an inclusive digital community?  


### Topics {-}

This unit is divided into the following topics:

1. Learning with Technology at TWU  
2. Digital Practices in the Workplace  
3. Societal Issues and the Internet  
4. Digital Wisdom  


### Learning Outcomes {-}

When you have completed this unit, you should be able to:

- Explore common digital tools used at Trinity Western University
- Discuss how technology has changed business practices in your field of interest or career.  
- Utilize technology to discover and share knowledge, collaborate with others, and become engaged digital global citizens  
- Describe societal issues and problematic online behaviours which have emerged in the digital world and how to deal with these challenges in an ethical manner  
- Create inclusive digital communities which embody a sense of belonging, connection, and Christian hospitality.
- Create a personalized narrative to document and express your learning process
- Practice evaluative judgment to document your process of learning in complex domains of knowledge


<!--

Course Learning Outcomes related to this unit: 
- Evaluate digital tools, platforms, and interactions based on ethical principles
- Develop personal and professional learning networks to discover and share knowledge, collaborate with others, and become engaged digital global citizens
- Create inclusive digital communities which embody a sense of belonging, connection, and Christian hospitality.
-->


### Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

```{block2, type='reflect'}

<span class="blockhead">Learning Activities</span>

- ...
- ...
 
**Note:** The learning activities in this course are designed to prepare you for the graded assigments in this course.  
You are strongly encouraged to complete them.


```

```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

- Assignment 3: Digital Literacy Portfolio  
*See the Assessment section in Moodle for assignment details*

```



### Resources {-}

- All resources will be provided online in the unit.  




<!--
comment
-->


## Learning with Technology at TWU 

### Activity: Why TWU? {-}

```{block2, type='reflect'}

Before we dive in to some digital tools you may use in your academic studies at Trinity, let's pause and think about what TWU means to you.  Why did you choose TWU?  What do you hope to achieve during your time here?

To give you some idea of what life is like at TWU, and why people choose TWU, watch the following video: [Discover being an International Student at Trinity Western University](https://www.youtube.com/watch?v=VkyZjv3ZbXg)


<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/VkyZjv3ZbXg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


What do you think? Share your thoughts by posting a comment on Discourse, for example:

- I'm excited to join the TWU community because ...
- I have questions about TWU: ...
- I am confident that ...
- I am concerned about ...

```

As you embark on your first year of study at TWU, what digital tools should you be familiar with?  What tools will be needed for your field of study?  Let's dive in to some common tech tools in academia. 

```{block, type='feedback'}
Note that the [***TWU Service Hub***](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=16267) is here to help!  Please reach out if you have any questions.) TWU also has a [Knowledge Base](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/) website with guides on using technology commonly used at TWU. has a number of articles to assist you with technology.  Please see the [Online Learning](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=4747) section and the [Information Technology](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=21800) section for help with the tools mentioned below.

```
#### Technology Proficency {-}

First, let's tackle what technical skills you will need as you start your studies.  As you read, check off skills you have acquired and feel comfortable using.


- [ ] Basic computer skills
- [ ] Sending/receiving email
- [ ] Sending and receiving attachments via email
- [ ] Using a web browser
- [ ] Finding resources through search engines (e.g. Chrome or Firefox)
- [ ] Downloading and installing software
- [ ] Familiarity with using browser plug-ins (e.g. PDF reader, video, audio)
- [ ] Using a word processing, presentation software, or other productivity applications
- [ ] Experience/familiarity with a variety of file formats such as: .pdf "Portable Document Format", .rtf "Rich Text Format", .doc or .docx "Microsoft Word Document", or .txt "Text document"
- [ ] The ability to be self-directed in learning new technology skills (e.g. following a handout, a step-by-step tutorial, online video help, or access to support to learn necessary skills)

This last skill is essential, as you will likely come across some tech tool that you need to figure out.  Consider how much you've learned in this course so far! You've got this!

#### Basic Technical Requirements {-}

This next section will outline basic hardware, software, applications, and accessories you will likely need as a TWU student. As you read, check off items you have, and/or feel comfortable using.

##### Hardware {-}  
- [ ] Computer - PC, Mac, Chromebook or tablet

##### Recommended Accessories {-}  
- [ ] Speakers, Microphone or Headphones  
- [ ] Video Camera (Webcam)  
- [ ] Scanner or Camera	  


##### Software {-}  
- [ ] Windows 10 or newer  
- [ ] Mac OS 10.14 or newer  
- [ ] Microsoft 365  

##### Internet Access & Connection {-}  
- [ ] Wi-Fi  
- [ ] High speed Broadband Internet Connection is Required  

***Recommended Internet speeds:***   
- Download speed of at least 25 mbps  
- Upload speed of at least 3 mbps  
- Ping response of less than 100ms  
Test your Internet speed using [speedtest.net](speedtest.net) 

Please consider the following while participating in online/hybrid courses:  
- Using a shared Internet connection will impact connectivity, such as additional household members use of streaming TV, gaming, and other Internet usage.  
- Wireless connections may be impacted by the distance from the router and interference from microwaves and other electronics. (Wired connections are recommended.)  
- Your Internet Service Provider’s performance may vary throughout the day based on community usage.



##### Internet Browsers {-}  
- [ ] The most recent release of Chrome or Firefox is recommended.  

##### Shared Drive, Sharing & Backup {-}

**[Data & Cloud Storage and Sharing](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=128533)**  
Cloud storage software provides web access to your online file storage, file sharing, and file synchronization. The only TWU approved Cloud Storage & Sharing services are:   
- [ ] [Microsoft OneDrive](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=71260)
- [ ] Microsoft SharePoint  
- [ ] OwnCloud](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=15681) 

The responsibility for storing TWU documents and files lies with the person who stores the data. Judgment is required about how and where TWU data will be stored.  

For more on Information Security, see the following guidelines:

(click to reveal)

TWU has a formal Information Security Policy and related Information Security Guidelines. This article provides some additional direction based on this set of policy and guidelines.  
Different data is governed by different regulations, laws, agreements, and rules; each requires different means of protection and reporting.  
 

**What about other 3rd party cloud storage solutions (Dropbox, Google Drive, Box, WeChat etc...)?**
In general, the use of unauthorized 3rd party cloud storage is not a good idea. TWU provides faculty and staff with the tools needed to collaborate internally and externally. The reasons below elaborate on the reasoning behind this position.  

*Lack of Visibility* - Since these software are not integrated into our network, there is no way we can retrieve data stored in these systems if an employee or faculty member leaves the institution and fails to disclose the usage of that account, or has it attached to a personal email account. If TWU data are present in those accounts, then it can be easily lost or compromised, which can lead to institutional and legal consequences.

*Lack of Accountability* - There is no way to effectively manage information security if a faculty or staff member is using unauthorized cloud storage. Additionally, there is no way to know if those data have been compromised and no ability for our forensics team to conduct analyses on these data in the event of a security incident.

*Lack of Support* - We don't offer technical support to these services. So, if something goes wrong, is lost or compromised, IT will have no way to help users who have lost data or been locked out of accounts.

*Collaboration* - We each have our own preferences when it comes to the various technologies we like to work with. There is not always a best tool for everyone. However, collaboration becomes more difficult when each individual or department selects there own collaboration platforms, prioritizing individual needs above the whole.

*Student Centred* - We will put students first. These guidelines ensure we are protecting information and ultimately protecting our students. We have been entrusted with a great deal of personal and private information and must ensure the decisions we make are protecting that information. 
 
**How to Share Data**
With Microsoft OneDrive and SharePoint, you can securely share files internally and externally. However, it is important to understand the different Data Classification levels and acceptable ways to share your files (Data Protection Guidelines).

Guidance Table for Sharing Data

| **Link Type**                        | **Confidential**             | **Sensitive**                | **Public**                                   |
|--------------------------------------|------------------------------|------------------------------|----------------------------------------------|
| **Specific People Internal User**    | Acceptable                   | Acceptable                   | Acceptable                                   |
| **Specific People External User**    | Acceptable Use good judgment | Acceptable Use good judgment | Acceptable                                   |
| **People in TWU (Internal Link)**    | Never                        | Acceptable Not Advisable     | Acceptable                                   |
| **Anyone with the link (Open Link)** | Never                        | Never                        | Acceptable Use expiration date when possible |


**Cyber security**
Learn how to protect your data and systems against security breaches.

SECURITY RECOMMENDATIONS
Protect yourself from Phishing attempts.
Enable Multi-Factor Authentication in your MyProfile page in PAWS.
Review USask's Information Technology Use and Security Policies.
Set a unique and strong password on your USask account.
Use a password manager for all of your accounts.
Back up your school work and files on OneDrive.
Int


##### Other Essential Links {-}  
Again, check the tools you are familiar with: 

- [ ] [Email](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=3351)

- [ ] [Moodle](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=8214)

- [ ] [TWU Library search engine](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=15050)

- [ ] [MS Teams](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=17821&SIDs=11353)

- [ ] [MS Stream](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=23454)

- [ ] [Zoom](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=17478)


#### Course Specific Tech Requirements {-}  
Some courses may require you to create surveys, e-portolfios, or other media.  We recommend the following:  

- [ ] [Survey Monkey](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=47076)  

- [ ] [WordPress](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=4746)  

- [ ] [Media Creation tutorials](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=6940) (A/V editing and tips)  


<!--

#### Learning Tools {-}

In this course, you have had the chance to explore a number of learning tools, including: [Obsidian](https://obsidian.md), [Hypothes.is](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=146716), [Zotero](https://www.zotero.org/), [LitMaps](https://www.litmaps.com/), [WordPress](https://create.twu.ca/) and more!

We anticipate those tools will help you think critically, collaborate, and ultimately succeed in your studies.

There is a plethora of other learning tools out there. We encourage you to explore various apps and evaluate them based on criteria you value (effectiveness, privacy, cost, data ownership, accessibility, etc.).



Search for the following apps/websites using the key words listed below.  Try adding "top" "best" "free" "university" "students" and see how that changes your search results.

- Note-taking Apps
- Annotate Web Resources
- Collaborative Tools
- Project Management Tools
- Graphic Organizers
- Study Tools
- Focus Tools
- Research Tools
- Writing Tools


<!--
give examples?
[Coggle: Simple Collaborative Mind Maps & Flow Charts](https://coggle.it/)
[MindMup](https://app.mindmup.com/)
[Canva](https://www.canva.com/)

-->


Other Technology Tips




## Digital Practices in Academia and the Workplace  

In this topic we consider how changes in technology have and will continue to impact digital practices in the workplace.  Pause and consider the following questions:

- How do professionals in your field of interest network online?  
- How has technology  changed business practices in your field of interest or career?  
- What are the implications for learning and skills development in your future career precipitated by changes in digital technology?  

### Activity: The Future of Work {-}

```{block2, type='reflect'}

In this short video, [Ken Steele](http://eduvation.ca/bio/){target="_blank"} from Eduvation speculates about the future of the labour market and the value of higher education in a digital age.

Watch [Higher Ed Trends: Student Career Anxiety and the Future of Work](https://www.youtube.com/watch?v=iY4UhfQefdU){target="_blank"}


<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/iY4UhfQefdU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


What do you think? Share your thoughts by posting a comment on Discourse, for example:

Higher ed is valuable because ...
- In a digital age ...
- I am confident that ...
- I am concerned about ...

```


### Technology and Change {-}

Throughout history, there are technologies which have influenced change in society. Consider for example, the invention of the steam engine and its contribution to the Industrial Revolution. In more recent times, the advent of digital photography displaced Kodachrome (at one time, the market leader in colour film sales) which ceased production in 2009.


### Activity: Newspaper and Music Industry in a Digital Age  {-}

```{block2, type='reflect'}

The readings which follow take a retrospective look at the impact of the Internet on the newspaper and music industries.

Please add or reply to annotations using [Hypothes.is](https://web.hypothes.is/){target="_blank"} sharing personal insights and experiences. Remember to tag your posts using the course code: LDRS101. 

1. Read [Chapter 3](https://www.bloomsburycollections.com/monograph-detail?docid=b-9781849666275&tocid=b-9781849666275-chapter3){target="_blank"} of Weller, M. (2011). [The Digital Scholar: How Technology is Changing Academic Practice](https://www.bloomsburycollections.com/monograph?docid=b-9781849666275){target="_blank"}. Bloomsbury Publishing PLC. (Direct [hypothes.is link](https://via.hypothes.is/https://www.bloomsburycollections.com/monograph-detail?docid=b-9781849666275&tocid=b-9781849666275-chapter3){target="_blank"}.)  
2. Read: [How streaming saved the music industry](https://www.theguardian.com/music/2018/apr/24/weve-got-more-money-swirling-around-how-streaming-saved-the-music-industry){target="_blank"}, published by the Guardian. (Direct [hypothes.is link](https://via.hypothes.is/https://www.theguardian.com/music/2018/apr/24/weve-got-more-money-swirling-around-how-streaming-saved-the-music-industry){target="_blank"}.)  
3. Read: [The future of newspapers in the digital age](https://medium.com/international-online-journalism/the-future-of-newspapers-in-the-digital-age-c7ac8a118312){target="_blank"}, published by Julien Sueres. (Direct [hypothes.is link](https://via.hypothes.is/https://medium.com/international-online-journalism/the-future-of-newspapers-in-the-digital-age-c7ac8a118312){target="_blank"}.)  

```


### Activity: Impact of Digital Technology on Business {-}

```{block2, type='reflect'}

Join the discussion on the impact of digital technology on business:

1. Choose any business or work environment (for example, your current career or future career)  
2.  Think about examples of how digital technology has had an impact on your chosen business over the last 30 years.  
3. State your business or work environment and share a practical example of how digital technology has influenced change in your chosen area:  
   - Has the example contributed to a fundamental change in the way things were done, or is this a minor change?  
   - Do you anticipate significant changes in your industry as a result of digital technology in the future? Provide an example.  

Please “Like”, share and reply to posts. These are forms of engagement and a contribution to your online learning identity. Remember to tag your posts using the course code: LDRS101.

```

### Artificial Intelligence {-}

Artificial intelligence (AI) is predicted to have a significant impact on society and business. Examples include, autonomous cars, computers understanding human speech and machine learning. Consider for instance, that computer chess games available for commercial desktop machines have the ability to beat accomplished chess players including grand masters.  And of course, Chat GPT.  

In this section we introduce a few interesting examples of artificial intelligence to provide a sense of how sophisticated these technologies are becoming.

First, let's define AI:

> "The theory and development of computer systems able to perform tasks normally requiring human intelligence, such as visual perception, speech recognition, decision-making, and translation between languages" ([Oxford Reference](https://www.oxfordreference.com/display/10.1093/oi/authority.20110803095426960){target="_blank"})

> "The capacity of a computer to perform operations analogous to learning and decision making in humans, as by an expert system, a program for CAD or CAM, or a program for the perception and recognition of shapes in computer vision systems" ([Dictionary.com](https://www.dictionary.com/browse/artificial-intelligence){target="_blank"})

What is your experience with AI?  Have you used an AI tool, such as Grammerly or ChatGPT? How has this technology affected you as a student, and what effect do you think it has/will have on your chosen profession?  

In the next activity, we'll explore some of these questions and concerns.

### Activity: How Can I Use AI as a Student? {-}

```{block2, type='reflect'}

First, do a quick search online for AI tools for university students. 
Examples:
- [How can AI be used by university students?](https://www.timeshighereducation.com/student/advice/how-can-ai-be-used-university-students){target="_blank"}  
- [The 10 Best AI Tools to Help Students Learn Faster](https://mystudylife.com/10-best-ai-tools-to-help-students-learn-faster/){target="_blank"}  

Intrigued? Do you find any tech tools that you might use to help you with understanding course topics, studying, generating flashcards, transcribing lectures and voice notes, grammar, writing an essay, creating a slideshow presentation, drafting a forum discussion post, etc.?

Do any of these capabilites concern you?  Do you think they concern your professors or fellow students? 

Review TWU's policy on [Academic Misconduct & Fraud](https://www.twu.ca/about-us/policies-guidelines/university-policies/academic-misconduct-fraud){target="_blank"}.

Search online for key words related to this issue, such as "university concern policy artificial intelligence" and you will find numerous articles on the use of AI in universities, as well as emerging policies.  For example, the University of Toronto's guidelines for [ChatGPT and Generative AI in the Classroom](https://www.viceprovostundergrad.utoronto.ca/strategic-priorities/digital-learning/special-initiative-artificial-intelligence/){target="_blank"}

Here is one more article that discusses the pros and cons for English Learners using AI in their studies: [Perspectives of the Use of ChatGPT as a Tool for Online Education of English](https://www.researchgate.net/publication/374483468_Perspectives_of_the_Use_of_ChatGPT_as_a_Tool_for_Online_Education_of_English){target="_blank"}

 

```

### Jobs and Automation {-}

In this section we consider the impact of automation on the future job market and the implications for education and training. Consider:

- Will robots replace humans?  
- What jobs are most at risk of being replaced by robots?  
- What are the implications for learning in a digital age?  

### Activity: Impact of Automation & AI in the Workplace {-}

```{block2, type='reflect'}

First, read [Collaborative Intelligence: Humans and AI Are Joining Forces](https://hbr.org/2018/07/collaborative-intelligence-humans-and-ai-are-joining-forces){target="_blank"} from Harvard Business Review.

Next, watch [*Humans Need Not Apply*](https://www.youtube.com/watch?v=7Pq-S557XQU){target="_blank"}

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/7Pq-S557XQU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

Finally, read [The Potential of Collaborative Intelligence for Social Media and Online Communities] by [Marcin Frąckiewicz](https://ts2.space/en/author/marcin/){target="_blank"}.

Consider your chosen field of study.  How can AI benefit your industry?  Are there any concerns regarding how AI might be used?

Share you thoughts on AI by posting a comment on Discourse, for example:

- AI will ...  
- I was surprised that AI ...  
- In <insert business> AI will ...  

```


### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```

## Topic

content

<!--
comment
-->



### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```

## Topic

**Digital Rights Management**

In a digital world, you may not have the full ownership rights you expect, or are accustomed to receiving in the physical world, when you buy digital content, resources, and equipment. In this section we explore digital rights management, geoblocking, and other examples. We highlight the importance users have to study the terms of reference and licenses when using proprietary software and buying products that rely on digital technology.

**Mini Challenge Summary**

**Summary:** Explore and discuss the impact of digital rights management. Time: 30–45 minutes. Consult the suggested resources and participate in the digital rights management debate.

<span class="prote">John Deere 9530 c.jpg</span>

**Digital Rights Management (DRM):** Digital rights management (DRM) describes the practice of imposing technical restrictions (hardware or software) to restrict what users can do with the digital content or operation of their equipment. 

**Examples include:**

- Film studios that embed software on their DVDs that restricts the number of copies a legal user can make to two.  
- Computer games that restrict the number of devices on which the game can be installed requiring server authentication to keep track of the number of installations.  
- e-Book publishers who restrict the ability to copy or print the materials.

**Reading**

- Layton, J. (Jan. 3, 2006). How Digital Rights Management Works. Retrieved July 4, 2017. (Click on the next button to progress the sub-pages of the article.)

**Geoblocking:** Geoblocking is a form of DRM which restricts access to content based on geographical location; for example, restrictions associated with media rights for sport coverage or films in different parts of the world because copyright holders sell broadcast and distribution rights to different companies around the world. Frequently, prices for streamed services of the same content will differ from country to country.

In another example, an individual who buys DVD films in one country and then emigrates to another country, may find that the playback of the legally purchased content is restricted by technology means in the new country of residence.

**Reading**

Geoblocking from Wikipedia;

EU lawmakers Include Spotify and iTunes in Geoblocking Ban from Reuters.

Case study - The Right to Repair

Do farmers have the right to repair their own tractors? Not necessarily, for example, John Deere’s proprietary software used to operate the vehicle does not allow “owners” to repair systems themselves and in effect they only have an implied license for life to operate the vehicle.

**Readings**

Choose one or two of the following readings (feel free to annotate using Hypothes.is and remember to tag your posts using the course code: lida102):

- We Can’t Let John Deere Destroy the Very Idea of Ownership from Wired.
- Why American Farmers are Hacking their own Tractors from the Guardian  
- A Right to Repair: Why Nebraska Farmers are Taking on John Deere and Apple from the Guardian.  
- The Fight for the “Right to Repair” from Smithsonian.com.  
- Outputs  

**Digital Rights Management Debate**

- Seeing both sides of a debate gives you the opportunity to better understand the issues. In this discussion, choose one of  

**the questions listed below and post to the DRM debate. Your post should include:**

- A sentence summarizing the issue.  
- The most important reason, in your opinion, why DRM is appropriate in a digital world.   
- The most important reason, in your opinion, why DRM is not appropriate in a digital world.  

<span class="blockhead">Questions to Consider (optional)</span>

- Do you have personal experience of a DRM issue? Summarize the example and present both sides of the issue.  
- Do you have personal experience of a geoblocking issue? Summarize the example and present both sides of the issue.  
- Should owners of equipment have the right to repair? Summarize the example and present both sides of the issue.

**Societal Issues and the Internet**

<span class="prote">Abstract crowd.jpg</span>

In this subunit, we introduce a number of societal issues and problematic online behaviors that have emerged in the digital world. Our list is not comprehensive and does not provide a thorough examination of the issues. Here, we encourage you to choose an issue for further investigation.

You will choose one societal issue or antisocial behavior associated with the Internet that you would like to investigate further and publish as an editorial in your course blog. You will base your focus on your reading of open access resources you find online. Your blog post will also help you build your online identity.

<!--
comment
-->

## Societal Issues and the Internet

In the final topic of this unit we introduce a number of societal issues and problematic online behaviours which have emerged in the digital world.

This is by no means a comprehensive list or a thorough examination of the respective issues. The selected issues are provided as a stimulus to help you choose an issue for further investigation.

### Activity: Quiz: Problematic Online Behaviours  {-}

```{block2, type='reflect'}

To test your knowledge of concepts associated with problematic behaviours online, we provide a short orientation quiz below. Once you have attempted your first answer, and in the event that you are not familiar or not sure what the alternatives mean, click on the options to find out more about the concept.

<iframe scrolling="yes" src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=575" allowfullscreen="allowfullscreen" width="100%" height="1000" frameborder="0" title="INNO 101 Unit 6.5  Activity: Quiz: Problematic Online Behaviours"></iframe>

<script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


Next, take the [Spot the Troll](https://spotthetroll.org/){target="_blank"} quiz developed by the Clemson University Media Forensics Hub which uses images of real social media content.

How did you do with the quizzes? Have you encountered any of these behaviours online? Share your thoughts by posting a comment on Discourse.


```


### Activity: The True Cost of Free Websites  {-}

```{block2, type='reflect'}

Watch this Matrix parody, a comedy skit published by CollegeHumour, depicting that if you are not paying for the service, you are not the consumer but the product. (Do you think this is a valid and reliable source for the topic?) [The Terrifying Cost of "Free” Websites | Adam Ruins Everything](https://www.youtube.com/watch?v=5pFX2P7JLwA){target="_blank"}

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/5pFX2P7JLwA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>


**Select one or more stimulus resources below:**

Read: [Stop Saying ‘If You’re Not Paying, You’re The Product’](https://www.techdirt.com/2012/12/20/stop-saying-if-youre-not-paying-youre-product/){target="_blank"}
Read: Krutka, D.G., Smits, R.M., and Willhelm, T.A. (2021) [Don’t Be Evil: Should We Use Google in Schools?](https://link.springer.com/article/10.1007/s11528-021-00599-4){target="_blank"} TechTrends. Association for Educational Communications & Technology.

**Corporate sponsored scientific research** 

- Read the Wikipedia article on [funding bias](https://en.wikipedia.org/wiki/Funding_bias){target="_blank"}  
- Read: Lundh, A., Krogsbøll, L. T., & Gøtzsche, P. C. (2012). [Sponsors’ participation in conduct and reporting of industry trials: a descriptive study](https://trialsjournal.biomedcentral.com/articles/10.1186/1745-6215-13-146){target="_blank"}. Trials, 13(1), 146.  
- Read the Wikipedia article on [ad blocking](https://en.wikipedia.org/wiki/Ad_blocking){target="_blank"}  

After viewing this resources, what do you think the cost of free websites is?

Please share your thoughts on Discourse and/or use Hypothes.is to annotate and share your comments.

```

### Activity: Forum: Philanthropy and corporate advertising  {-}

```{block2, type='reflect'}

Read the following case study:

The [OERu](https://oeru.org/){target="_blank"} is a charitable organisation which provides open online courses for free, using open educational resources which any educational institution can adopt, modify and reuse. There are costs that need to be covered to sustain the OERu: for example, the assembly of open online courses, hosting of the server and software infrastructure, staff to coordinate and support the initiative. etc. The OERu does not generate any revenue from corporate services, by, for example, allowing advertising on the OERu course sites for a share of the advertising revenue. Moreover, the OERu does not sell or generate revenue from personal data learners provide by using these free learning services, therefore users are not the product of this service.   

**Discussion**

Join the discussion on philanthropy and corporate advertising. The key question is how can non-profit organisations sustain free educational services for those who can’t afford traditional education provision?

Consider the following issues:

- As a learner, how would you feel if the course materials included corporate advertising? If advertising were to be supported, how would you feel if the OERu course sites required you to switch off any ad-blockers before gaining access to the course materials?  
- Is it appropriate for publicly funded institutions and charities working in education to generate revenue from corporate advertising to support and sustain free online services? What are the risks and opportunities?    
- Should education institutions and educational charities accept significant corporate sponsorship in return for profiling proprietary products?  
- The OERu has recommended that learners use free blogging services to share their learning outputs. Many of these services carry advertising. How do you feel about using these services – being the product rather than consumer? Would it be better for OERu to recommend that learners use a paid service without advertising? How would this impact on learners who do not have sufficient funds to afford maintaining a domain of their own?  
- Other?  

Remember to tag your posts using the course code: LDRS101

```

### Net Neutrality {-}

> *“The Web as I envisaged it, we have not seen it yet. The future is still so much bigger than the past.”*
>
>***— Time Berners-Lee***

The World Wide Web was originally designed to provide universal access to a large universe of documents. To achieve universal access, it was paramount to design the web as an open system without a central locus of control. However, on the Internet there are an increasing number of “walled gardens” that aim to control user’s access to content and services. In this section we explore the concept of net neutrality and reflect on the risks associated with universal access to online information.


### Activity: The Meaning of Net Neutrality  {-}

```{block2, type='reflect'}

Watch [Net Neutrality Explained](https://www.youtube.com/watch?v=p90McT24Z6w){target="_blank"}

<div class ="video-container">

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/p90McT24Z6w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> 

</div>

This video was produced in 2015, where the main concern of net neutrality seemed to relate to companies controlling our access to information on the internet.  Notice around the 2 minute mark where opposing political parties are supported/blamed for their view on the topic.)

Fast forward to 2023 where the concern is now government oversight in what information we see.

This issue is highly controversial and politisized.  If you are interested in exploring the topic...which means encountering diverse views on the subject, then read on!  As we learn with technology in this course and in life, we need to critically evaluate the information available on the internet and whether there are any restrictions on information that would help us as citizens to make informed decisions.

If interested, peruse the following resources.  ***Trigger alert!***  These perspective range from liberal to conservative points of view. This course aims to promote critical thinking of what we consume and produce online. Refer back to the video [Building More Creative Social Networks](https://www.youtube.com/watch?v=Acc4zY1sQ0o){target="_blank"}.  Will encountering an opposing point of view contribute to your understanding of an issue?

Let's dig in to some points on net neutrality!

<details>
<summary>**Facebook Zero: Am Attempt to Bring Access to All?**</summary>

Consider the following case study:

"[Facebook Zero](https://en.wikipedia.org/wiki/Facebook_Zero){target="_blank"} is an application for mobile devices and business agreements with a number of companies to provide access to selected internet services without incurring data charges targeting markets where internet access may be less affordable. Facebook Zero is part of internet.org set up by Facebook and the basic websites than can be accessed for free without data charges are determined by the initiative."

...and then some criticism:

> "Facebook Zero became controversial in some countries due to several issues such as net neutrality.[9] For instance, India's Telecom Regulatory Authority (TRAI) bans zero-rated services on account of "discriminatory tariffs for data services on the basis of content”.[13] A criticism also stated that Facebook is practicing digital colonialism because it is not introducing open internet but building a "little web that turns the user into a mostly passive consumer of mostly western corporate content”.[11]"

Is the Internet Neutral in Canada?  

Search online for various views on this topic.  Here are a couple to get you started:  
[Bill C-18: The fallout over Google, Meta's plans to block news links in Canada](https://www.youtube.com/watch?v=W5YLvCEd1yE)


[Debating Bill C-11—Internet Censorship for Canadians](https://www.youtube.com/watch?v=bmd4sASKFRw){target="_blank"}


search for "Canada's New Regulations for Podcasts"

Is the Internet Neutral in America?

[Net Neutrality is BACK! FCC tries to take away internet freedom AGAIN!](https://www.youtube.com/watch?v=DCfWzAM-JeY) from Redacted w Clayton Morris


Poilievre: Warned about Justin Trudeau's online censorship law | Latest News | WION


Is the Internet Neutral in Africa?

[Who really wins from Facebook's 'free internet' plan for Africa?](https://www.zdnet.com/article/who-really-wins-from-facebooks-free-internet-plan-for-africa/){target="_blank"}



In addition to the challenges associated with net neutrality, think about how closed technologies can build walled gardens, for example:

- The Apple iOS which is restricted to running pre-approved applications on the hardware purchased by the user.  
- The Amazon Kindle line of e-readers intentionally designed to favour the Amazon commercial ecosystem.  
- Video game consoles that typically require game developers to purchase a license to develop games for the platform frequently requiring approval from the platform prior to publishing the games.  



Resources

- internet.org by Facebook  
- India bans Facebook’s basics app to support net neutrality  
- Facebook’s Internet.org Isn’t Going Over Well in India  


Share your thoughts on net neutrality by posting a comment on Discourse, for example:

- Net neutrality is important because ...  
- Net neutrality can / can’t coexist with internet.org because ...  
- Free basics is a good thing because ...  
- Free basics is problematic because ...  

You must be logged in to post to WEnotes.



</details>

<details>
<summary>**title of article**</summary>

text

</details>

<details>
<summary>**title of article**</summary>

text

</details>

<details>
<summary>**title of article**</summary>

text


</details>


<details>
<summary>**title of article**</summary>

text


</details>


```

### Activity: Is there Net Neutrality Today?  {-}

```{block2, type='reflect'}




```


### Activity: Forum: Philanthropy and corporate advertising  {-}

```{block2, type='reflect'}


```


### Activity:   {-}

```{block2, type='reflect'}


```


### Activity:   {-}

```{block2, type='reflect'}


```


### Activity:   {-}

```{block2, type='reflect'}


```


### Activity:   {-}

```{block2, type='reflect'}


```




### Activity:  {-}

```{block2, type='reflect'}

Watch/read...

<span class="blockhead">Questions to Consider</span>

After completing the activities above, answer the following questions:

- ...

```

## Digital Wisdom

To conclude our course, we will examine another perspective on ethics and technology.  This may tap into the foundational lens by which you approach many ethical issues, so take a moment to reflect on the following:

- What role does technology play in my social, academic, and spiritual life?  
- What guidance does the Bible have on our use of technology today?  
- How will my use of technology support my social, academic, and spiritual goals?  
  
### Activity: Digital Wisdom  {-}

```{block2, type='reflect'}

Skim the following article in which the authors present a framework for digital wisdom, as well as practical practices that can help navigate the digital in our daily lives. 

- [A Framework for Digital Wisdom in Higher Education](https://christianscholars.com/a-framework-for-digital-wisdom-in-higher-education/){target="_blank"}

Here are some quotes that resonate with me.  Feel free to highlight your quotes using Hypothes.is, or in your personal Obsidian notes.  

> "Institutions of higher education have a crucial role and responsibility at this moment of technological change to form people who will flourish in our so-called digital age." (para 1)

> "Within the context of Christian higher education, the need to integrate new ICTs into our individual and institutional lives well and wisely—as we consider what technologies are doing to us and what we will do with them—is of utmost significance if we are committed to the cultivation of competence, character, and wisdom." (para 6)

> "Scripture enables us look behind and beyond our and others’ online identities to see ourselves and others as embodied and relational beings made in the image of God." (para 21)

> "Our use of technologies must be shaped by our intentions and values, and we must be aware of how platform interfaces, permissions, algorithms, and other design elements could interfere with our goals and obligations." (para 31)

<span class="blockhead">Questions to Consider</span>

Answer the following questions in your personal journal:  

- How can you, as a TWU student, flourish in this digital age?  
- How do the tools you use shape you? How do you use them wisely?  
- How should we view and relate to others online - in particular those whom we disagree with?   
- How can you cultivate inclusive digital communities which embody a sense of belonging, connection, and Christian hospitality?  
- And finally, how can we use technology in a way that aligns with our intentions and values?  
 

```



## Summary {-}

In this unit, you have had the opportunity to learn about ...

Finally, we've presented the idea of digital wisdom.  As you continue with the last two units of the course, we want to encourage you to examine your purpose in using technology, as well as how your contributions online can benefit others.  As a final thought before your evaluate your own learning in this unit, consider TWU's mission and vision statements and how they relate to you and what you can offer to serve others and glorify God.

As you complete this course and continue on your learning journey we hope you have aquired skills that will prepare you for your academic studies and professional career.  

... tools are more prepared for (and moticvated to) be an engaged digital global citizen.

Create inclusive digital communities which embody a sense of belonging, connection, and Christian hospitality.  
Develop personal and professional learning networks to discover and share knowledge, collaborate with others, and 

> "The mission of Trinity Western University, as an arm of the Church, is to develop godly Christian leaders: positive, goal-oriented university graduates with thoroughly Christian minds; growing disciples of Jesus Christ who glorify God through fulfilling the Great Commission, serving God and people in the various marketplaces of life."

> "Every graduate is equipped to think truthfully, act justly, and live faithfully for the good of the world and the glory of God."   
> [TWU Mission & Vision Statements](https://www.twu.ca/about-us/commitments/mission-vision){target="_blank"}

## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Quizzes 1 & 2</span>

After completing this unit, including the learning activities, you are asked to complete ...

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- ...
- ...
 

```
