# Assessment {.unnumbered}

The following assignments are opportunities for learners to demonstrate their understanding of the course outcomes. Please confirm assignment details with your instructor, referring to the course syllabus.

Note that Assignment dropboxes are located in Moodle. Also refer to the Course Schedule in Moodle for the specific due dates.

## Assignment 1: Learning Journal {.unnumbered}

-   Obsidian journal,
-   Concept map
-   V&R diagram map

### Part 1: Learning Journal

After completing Units 1-3, including the learning activities, you are asked to share your learning journal as a 'work-in-progress' demonstrating the knowledge and skills you have gained thus far in the course. This assignment is based on the learning activities in Units 1-3, and is designed to demonstrate your understanding of the course learning outcomes (#1-4).

Examine the learning outcomes for each unit and ensure that your journal addresses each outcome. Include your thoughts from the learning activities, and be sure to apply concepts to your experiences and/or current events. I am especially looking for your personal reflection on your learning process.

Note that this is a chance to present your understanding and application of the course material, ask questions, clarify issues, and connect with your instructor. I am looking for evidence that you are engaging the course material.

To help you make connections and develop your critical thinking skills, you are asked to include a mind map of the three units. Mind maps are useful tools not only to organize your notes, but will help you process your learning in this course. You should use [Obsidian](https://obsidian.md/) to complete this mind map.

You will submit your journal, including your mind map, as part of Assignment 1. You may also use your journal to meet the requirements of Assignments 2 and 3, as each assignment builds on the skills learned in each unit.

#### See the Assessment section in Moodle for the Grading Rubric.

### Part 2: Assessment Conversation

In addition to submitting your journal you will meet with your instructor and have an assessment conversation. What does this mean? This conversation is an opportunity for you to explain your learning process and demonstrate your understanding of the course learning outcomes.

*How to Prepare for your Assessment Conversation:*

1.  Review the course learning outcomes (#1-4) and take notes on how you would explain your understanding of them. This is an opportunity for self-reflection and assessment.
2.  Review your Journal entries that should demonstrate how you have met the targeted course learning outcomes.
3.  Review your mind map and V&R diagram and be able to show connections between concepts, apply concepts to your experiences and/or current events, and demonstrate personal reflection and critical thinking.

*Before the Assessment Conversation:*

1.  Set up a time to meet with your instructor by using the Scheduling Assistant.
2.  You will be given a Zoom link. Be sure to test your video and audio, and click on the link a couple minutes before your allotted time to allow for technical interruptions.

*During the Assessment Conversation:*

1.  After a brief introduction, you will be asked a series of questions designed to assess your understanding of the course learning outcomes.
2.  During the conversation, make sure you clearly explain how your Learning Journal demonstrates your knowledge and skills related to the course outcomes.
    -   *Note: Do not read verbatim your assignments or reflections, but highlight your key learning.* E.g. What do you want your instructor to notice? Which indicators of proficiency have been met? What are you especially proud of? How does your journal demonstrate evidence of learning?
3.  Your instructor will provide you with feedback to help you assess whether or not you have met the proficiency criteria. They will also give suggestions for improvement and encouragement.
4.  Take notes of the feedback and reflect on how you can continue to grow in each of the learning outcome areas.

##### Proficiency Levels

| **Emerging**                                                                                                              | **Developing**                                                                                                           | **Proficient**                                                                                                            | **Extending**                                                                                                                  |
|------------------|------------------|------------------|-------------------|
| The student demonstrates an **initial** understanding of the concepts and competencies relevant to the expected learning. | The student demonstrates a **partial** understanding of the concepts and competencies relevant to the expected learning. | The student demonstrates a **complete** understanding of the concepts and competencies relevant to the expected learning. | The student demonstrates a **sophisticated** understanding of the concepts and competencies relevant to the expected learning. |

##### Grading Rubric

| **TWU SLO Categories**                        | **Course Learning Outcomes** **I can...** | **Evidence of Learning** **I can demonstrate this through...** | **Level of Proficiency** |
|-----------------|----------------|-----------------------|----------------|
|                                               |                                           |                                                                |                          |
| **Knowledge + Application**                   |                                           |                                                                |                          |
| **Cognitive Complexity**                      |                                           |                                                                |                          |
| **Aesthetic Expression and Interpretation**   |                                           |                                                                |                          |
| **Inter/Intra Personal Awareness**            |                                           |                                                                |                          |
| **Spiritual Formation**                       |                                           |                                                                |                          |
| **Social Responsibility & Global Engagement** |                                           |                                                                |                          |


## Assignment {.unnumbered}

Assignment 2: Digital Citizenship Blog

### Part 1: Blog Posts

After completing Units 1-5, including the learning activities, you are asked to share your blog posts demonstrating the knowledge you have gained on the concept of digital citizenship.

This assignment is based on the learning activities in Units 4 and 5, as well as the skills practices in previous units. Note that you can control the privacy settings of each blog post (e.g., so only your instructor can see it, or for the TWU community, or open access for all). For some activities you may have chosen to complete them in your Learning Journal. Please share any relevant entries to demonstrate your understanding of the course learning outcomes.

### Part 2: Written Reflection:

Prepare a learning reflection of about 500–600 words reflecting on the development of your understanding of digital citizenship.

In your Reflective post, provide the following:\
- your personal description of digital citizenship;\
- your revised definition of digital citizenship based on your research of the topic;\
- list of university-level study examples of the elements of digital citizenship;\
- a summary of the primary rights and responsibilities for learning in a digital age;

To help you structure your writing, see the following video on [**Reflective Writing**](https://www.youtube.com/watch?v=SntBj0FIApw)

Your post should cover the following aspects:

**D**: Describe what happened. What was a highlight from our discussion on digital citizenship?\
**I**: Interpret the events. How did it make you feel? What was “good” and “bad” about the experience?\
**E**: Evaluate the effectiveness. What did you learn from it? How beneficial or useful was this discussion?\
**P**: Plan for the future. What new knowledge or skills do you have and how will your experience inform future learning?

Add a category or tag for your post using the course tag: ldrs101. Post a comment on one or two blog contributions.

### Part 2: Video Reflection

For the second part of this assignment, you are asked to create a short video (under 5 minutes) describing your learning process as it relates to our course learning outcomes. Reflect on your demonstration of the following skills:

1.  Build and customize technology-integrated workflows to enhance and enrich your learning journey.
2.  Apply digital literacy skills to evaluate the legitimacy, credibility and reliability of online resources for academic study.
3.  Practice evaluative judgment to document your process of learning in complex domains of knowledge.
4.  Create a personalized narrative to document and express your learning process
5.  Evaluate digital tools, platforms, and interactions based on ethical principles.
6.  Develop personal and professional learning networks to discover and share knowledge, collaborate with others, and become engaged digital global citizens.
7.  Create inclusive digital communities which embody a sense of belonging, connection, and Christian hospitality.

You are encouraged to post your video reflection on your blog. Remember that you control the privacy settings, so you can share your video blog with the instructor, your peers, and others outside Trinity if you wish.

Notes:

LDRS 101: Learning with Technology

*Assessment for, of, and as Learning*

# Course Learning Evaluation:

The course grade will be determined by the satisfactory completion of all requirements.

| **Assessment**                                                         | **Assesses Course Learning Outcome** |
|-----------------------------------------------|-------------------------|
| **Assignment 1: Learning Journal** & Assessment Conversation           | 1-4                                  |
| **Assignment 2: Digital Citizenship Blog** & Video Reflection          | 1-7                                  |
| **Assignment 3: Digital Literacy Portfolio** & Assessment Conversation | 1-7                                  |

###### Notes on Grading:

In this course, we use the SOLO Taxonomy. SOLO stands for *Structure of the Observed Learning Outcome* and is a gauge to help learners and the instructor ensure that assignments are written at an appropriate level.

| **Pre-Structural**    | A pre-structural response completely **misses the point** of the assessment.                                                                                                                                                   |
|-------------|----------------------------------------------------------|
| **Uni-Structural**    | A uni-structural response displays knowledge or ability in **one dimension of the construct**.                                                                                                                                 |
| **Multi-Structural**  | A multi-structural response displays knowledge or ability in **multiple dimensions of the construct**, but each dimension is **disconnected** from the others.                                                                 |
| **Relational**        | A relational response displays knowledge or ability in **multiple dimensions of the construct, and how they are related to each other**.                                                                                       |
| **Extended Abstract** | An extended abstract response displays knowledge or ability in **multiple dimensions of the construct, how they are related to each other, and how that construct can be applied to help us understand different constructs**. |

**How does this translate into a grade?** If you are providing responses at a pre- or uni-structural level in a university course, you will receive a grade below C. Multi-structural responses will lead to grades in the 'C' range. At minimum, your responses should be unambiguously relational for a grade in the 'B' range and extended abstract for a grade in the 'A' range.

[@madland2024]